/** Catálogo expandido — +52 produtos (total 106) */
(function (w) {
  'use strict';

  function ecImg(id) {
    return "https://images.unsplash.com/" + id + "?w=800&h=800&fit=crop&fm=jpg&q=92&auto=format";
  }

  var premium = [
    { id: 'p31', brand: 'Motorola', name: 'Moto Edge 40 Neo 256GB', shop: 'Mercadopamina', price: 2499, oldPrice: 2999, tag: 'Android', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.5, reviews: 3438, prime: true, specs: ['Tela pOLED 6,4" 144Hz', 'Dimensity 7030 · 256GB', 'Câmera 50MP OIS', '5G · NFC', 'IP68'], desc: 'Tela pOLED 6,4" 144Hz — Moto Edge 40 Neo 256GB.' },
    { id: 'p32', brand: 'Xiaomi', name: 'Redmi Note 13 Pro 5G 256GB', shop: 'Mercadopamina', price: 1899, oldPrice: 2299, tag: 'Android', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.7, reviews: 5385, prime: true, specs: ['Tela AMOLED 6,67" 120Hz', 'Snapdragon 7s Gen 2', 'Câmera 200MP', 'Carregamento 67W', 'IP54'], desc: 'Tela AMOLED 6,67" 120Hz — Redmi Note 13 Pro 5G 256GB.' },
    { id: 'p33', brand: 'Google', name: 'Pixel 8 Pro 128GB', shop: 'Mercadopamina', price: 5999, oldPrice: 6999, tag: 'Android', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.9, reviews: 10705, prime: true, specs: ['Tensor G3 · IA Google', 'Tela LTPO 6,7" 120Hz', 'Câmera Pro com Magic Eraser', '7 anos de updates', 'IP68 titânio'], desc: 'Tensor G3 · IA Google — Pixel 8 Pro 128GB.' },
    { id: 'p34', brand: 'Sony', name: 'Controle DualSense PS5 — Branco', shop: 'Mercadopamina', price: 449, oldPrice: 549, tag: 'Games', image: ecImg('photo-1606813907291-d86efa9b94db'), rating: 4.4, reviews: 2543, prime: true, specs: ['Feedback háptico', 'Gatilhos adaptativos', 'Microfone integrado', 'Trackpad touch', 'Bluetooth e USB-C'], desc: 'Feedback háptico — Controle DualSense PS5 — Branco.' },
    { id: 'p35', brand: 'Microsoft', name: 'Xbox Series X 1TB', shop: 'Mercadopamina', price: 4499, oldPrice: 4999, tag: 'Games', image: ecImg('photo-1606813907291-d86efa9b94db'), rating: 4.4, reviews: 526, prime: true, specs: ['4K até 120fps', 'SSD 1TB', 'Ray tracing', 'Quick Resume', 'Controle sem fio incluso'], desc: '4K até 120fps — Xbox Series X 1TB.' },
    { id: 'p36', brand: 'Valve', name: 'Steam Deck OLED 1TB', shop: 'Mercadopamina', price: 5499, oldPrice: 5999, tag: 'Games', image: ecImg('photo-1621259182978-fbf93132d53d'), rating: 4.4, reviews: 12134, prime: true, specs: ['Tela OLED 7,4" HDR', 'AMD APU Zen 2', '1TB NVMe', 'SteamOS · biblioteca PC', 'Áudio aprimorado'], desc: 'Tela OLED 7,4" HDR — Steam Deck OLED 1TB.' },
    { id: 'p37', brand: 'Razer', name: 'DeathAdder V3 Pro — Preto', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Periféricos', image: ecImg('photo-1527864550417-7fd91fc51a46'), rating: 4.4, reviews: 15040, prime: true, specs: ['Sensor Focus Pro 30K', '63g ultraleve', 'Switch óptico Gen-3', 'Até 90h bateria', 'HyperSpeed wireless'], desc: 'Sensor Focus Pro 30K — DeathAdder V3 Pro — Preto.' },
    { id: 'p38', brand: 'Corsair', name: 'K70 RGB PRO Mecânico', shop: 'Mercadopamina', price: 799, oldPrice: 999, tag: 'Periféricos', image: ecImg('photo-1527864550417-7fd91fc51a46'), rating: 4.8, reviews: 10726, prime: true, specs: ['Switch Cherry MX Red', 'Alumínio escovado', 'RGB por tecla', 'Anti-ghosting full', 'USB passthrough'], desc: 'Switch Cherry MX Red — K70 RGB PRO Mecânico.' },
    { id: 'p39', brand: 'Samsung', name: 'Galaxy Buds3 Pro', shop: 'Mercadopamina', price: 1299, oldPrice: 1499, tag: 'Áudio', image: ecImg('photo-1590658268037-6bf12165a8df'), rating: 4.7, reviews: 15229, prime: true, specs: ['ANC inteligente', 'Áudio 360 com head tracking', 'IP57', 'Até 30h com case', 'Compatível Galaxy e Android'], desc: 'ANC inteligente — Galaxy Buds3 Pro.' },
    { id: 'p40', brand: 'Bose', name: 'QuietComfort Ultra Earbuds', shop: 'Mercadopamina', price: 2299, oldPrice: 2599, tag: 'Áudio', image: ecImg('photo-1590658268037-6bf12165a8df'), rating: 4.4, reviews: 14647, prime: true, specs: ['ANC líder Bose', 'Immersive Audio', 'Até 6h + 24h case', 'IPX4', 'Multipoint Bluetooth'], desc: 'ANC líder Bose — QuietComfort Ultra Earbuds.' },
    { id: 'p41', brand: 'Marshall', name: 'Emberton II — Preto', shop: 'Mercadopamina', price: 999, oldPrice: 1199, tag: 'Áudio', image: ecImg('photo-1608043152269-423dbba4e7e1'), rating: 4.7, reviews: 5964, prime: true, specs: ['Som Marshall signature', 'IP67 portátil', '30h bateria', 'Bluetooth 5.3', 'Design vintage compacto'], desc: 'Som Marshall signature — Emberton II — Preto.' },
    { id: 'p42', brand: 'GoPro', name: 'HERO12 Black', shop: 'Mercadopamina', price: 2499, oldPrice: 2799, tag: 'Creator', image: ecImg('photo-1516035069371-29a1b244cc32'), rating: 4.8, reviews: 6522, prime: true, specs: ['Vídeo 5,3K60 HDR', 'HyperSmooth 6.0', '10m à prova d\'água', 'Telas frontal e traseira', 'Live streaming'], desc: 'Vídeo 5,3K60 HDR — HERO12 Black.' },
    { id: 'p43', brand: 'Insta360', name: 'X4 360° 8K', shop: 'Mercadopamina', price: 3299, oldPrice: 3699, tag: 'Creator', image: ecImg('photo-1516035069371-29a1b244cc32'), rating: 4.8, reviews: 7120, prime: true, specs: ['Vídeo 8K 360°', 'FlowState estabilização', 'À prova d\'água', 'Edição automática no app', 'Ideal para esportes e viagem'], desc: 'Vídeo 8K 360° — X4 360° 8K.' },
    { id: 'p44', brand: 'Polaroid', name: 'Now+ Gen 2 — Branco', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Foto', image: ecImg('photo-1516035069371-29a1b244cc32'), rating: 4.6, reviews: 5022, prime: false, specs: ['Impressão instantânea', 'Controle via app Bluetooth', 'Modos criativos dupla exposição', 'Bateria recarregável USB-C', 'Filme i-Type e 600'], desc: 'Impressão instantânea — Now+ Gen 2 — Branco.' },
    { id: 'p45', brand: 'Braun', name: 'Series 9 Pro 9465cc', shop: 'Mercadopamina', price: 1899, oldPrice: 2199, tag: 'Beleza', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.4, reviews: 12444, prime: true, specs: ['5 elementos de corte', 'Cabeça SyncroSonic', 'Estação Clean&Charge', 'À prova d\'água', 'Barbear seco e molhado'], desc: '5 elementos de corte — Series 9 Pro 9465cc.' },
    { id: 'p46', brand: 'Oral-B', name: 'iO Series 10 — Preto', shop: 'Mercadopamina', price: 1299, oldPrice: 1499, tag: 'Beleza', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.5, reviews: 1136, prime: true, specs: ['Tecnologia iO micro-vibração', '7 modos de escovação', 'Detecção IA de áreas', 'Display inteligente', 'App Oral-B'], desc: 'Tecnologia iO micro-vibração — iO Series 10 — Preto.' },
    { id: 'p47', brand: 'Dyson', name: 'Airwrap Complete Long', shop: 'Mercadopamina', price: 3999, oldPrice: 4499, tag: 'Beleza', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.5, reviews: 7315, prime: true, specs: ['Coanda airflow technology', 'Modela, seca e alisa', '6 acessórios inclusos', '3 velocidades e 3 temperaturas', 'Para cabelos longos'], desc: 'Coanda airflow technology — Airwrap Complete Long.' },
    { id: 'p48', brand: 'GHD', name: 'Platinum+ Styler — Preto', shop: 'Mercadopamina', price: 1499, oldPrice: 1799, tag: 'Beleza', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.8, reviews: 12705, prime: true, specs: ['Tecnologia ultra-zone 185°C', 'Placas flutuantes', 'Até 70% mais forte e 2× mais rápido', 'Modo sono automático', 'Cabos longos 2,7m'], desc: 'Tecnologia ultra-zone 185°C — Platinum+ Styler — Preto.' },
    { id: 'p49', brand: 'Google', name: 'Nest Learning Thermostat', shop: 'Mercadopamina', price: 1299, oldPrice: 1499, tag: 'Casa', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.6, reviews: 10738, prime: false, specs: ['Aprende sua rotina', 'Controle por app e voz', 'Economia de energia', 'Compatível Alexa e Google', 'Instalação profissional'], desc: 'Aprende sua rotina — Nest Learning Thermostat.' },
    { id: 'p50', brand: 'Amazon', name: 'Echo Dot 5ª geração', shop: 'Mercadopamina', price: 349, oldPrice: 449, tag: 'Casa', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.4, reviews: 8259, prime: true, specs: ['Alexa integrada', 'Som melhorado', 'Hub de casa inteligente', 'Controle de dispositivos Zigbee', 'Design compacto'], desc: 'Alexa integrada — Echo Dot 5ª geração.' },
    { id: 'p51', brand: 'Ring', name: 'Video Doorbell Wired', shop: 'Mercadopamina', price: 499, oldPrice: 599, tag: 'Casa', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.7, reviews: 8646, prime: true, specs: ['Vídeo HD ao vivo', 'Detecção de movimento', 'Áudio bidirecional', 'Alertas no celular', 'Instalação simples'], desc: 'Vídeo HD ao vivo — Video Doorbell Wired.' },
    { id: 'p52', brand: 'TP-Link', name: 'Deco X55 Wi-Fi 6 Mesh (3 pack)', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Periféricos', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.9, reviews: 15053, prime: true, specs: ['Cobertura até 650m²', 'Wi-Fi 6 AX3000', '3 unidades mesh', 'App Deco fácil setup', 'Ideal para fibra residencial'], desc: 'Cobertura até 650m² — Deco X55 Wi-Fi 6 Mesh (3 pack).' },
    { id: 'p53', brand: 'LG', name: 'Lava e Seca VC5 11kg Inverter', shop: 'Mercadopamina', price: 3999, oldPrice: 4599, tag: 'Eletro', image: ecImg('photo-1585655097312-7c098090a426'), rating: 4.4, reviews: 6286, prime: false, specs: ['Lava e seca 11kg', 'Motor Direct Drive Inverter', 'Steam hygienic', 'App ThinQ', '1400 RPM'], desc: 'Lava e seca 11kg — Lava e Seca VC5 11kg Inverter.' },
    { id: 'p54', brand: 'Brastemp', name: 'Lavadora 12kg Turbo Economia', shop: 'Mercadopamina', price: 2199, oldPrice: 2599, tag: 'Eletro', image: ecImg('photo-1585655097312-7c098090a426'), rating: 4.8, reviews: 6771, prime: false, specs: ['12kg capacidade', '15 programas de lavagem', 'Turbilhonamento Turbo', 'Painel digital', 'Economia de água e energia'], desc: '12kg capacidade — Lavadora 12kg Turbo Economia.' },
    { id: 'p55', brand: 'Electrolux', name: 'Purificador PE12B Gelada', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Cozinha', image: ecImg('photo-1626082927389-6cd097cdc6ec'), rating: 4.8, reviews: 5166, prime: true, specs: ['Água gelada, natural e quente', 'Filtro com alerta de troca', 'Design compacto bancada', 'Economia vs galão', 'Instalação rápida'], desc: 'Água gelada, natural e quente — Purificador PE12B Gelada.' },
    { id: 'p56', brand: 'Midea', name: 'Ar Split Inverter 12000 BTU', shop: 'Mercadopamina', price: 1899, oldPrice: 2299, tag: 'Eletro', image: ecImg('photo-1585655097312-7c098090a426'), rating: 4.4, reviews: 7879, prime: false, specs: ['12000 BTU quente/frio', 'Tecnologia inverter A+++', 'Wi-Fi opcional via app', 'Modo silencioso sleep', 'Ideal para até 18m²'], desc: '12000 BTU quente/frio — Ar Split Inverter 12000 BTU.' },
  ];

  var fashion = [
    { id: 'm25', brand: 'Hermès', brandTier: 'griffe', category: 'Acessórios', name: 'Birkin 30 Togo Gold', shop: 'Mercadopamina', price: 89900, oldPrice: 95000, tag: 'Alta costura', image: ecImg('photo-1548036328-c9fa89d128fa'), rating: 4.4, reviews: 10650, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Couro Togo artesanal', 'Ferragem palladium', 'Alças estruturadas', 'Forro caprine', 'Peça de investimento'], desc: 'Birkin 30 Togo Gold — Hermès.' },
    { id: 'm26', brand: 'Dior', brandTier: 'griffe', category: 'Acessórios', name: 'Saddle Bag Canvas Oblique', shop: 'Mercadopamina', price: 12900, oldPrice: 14500, tag: 'Griffe', image: ecImg('photo-1566150905458-1bf1fc113f0d'), rating: 4.4, reviews: 1454, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Canvas Dior Oblique', 'Formato saddle icônico', 'Correia ajustável', 'Fecho magnético CD', 'Edição clássica'], desc: 'Saddle Bag Canvas Oblique — Dior.' },
    { id: 'm27', brand: 'YSL', brandTier: 'griffe', category: 'Acessórios', name: 'Loulou Medium Matelassê Preto', shop: 'Mercadopamina', price: 9900, oldPrice: 11500, tag: 'Griffe', image: ecImg('photo-1548036328-c9fa89d128fa'), rating: 4.7, reviews: 9041, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Couro matelassê Y-quilt', 'Corrente dourada', 'Logo YSL frontal', 'Interior organizado', 'Ombro ou crossbody'], desc: 'Loulou Medium Matelassê Preto — YSL.' },
    { id: 'm28', brand: 'Valentino', brandTier: 'griffe', category: 'Calçados', name: 'Rockstud Pump 100mm Nude', shop: 'Mercadopamina', price: 4590, oldPrice: 5200, tag: 'Griffe', image: ecImg('photo-1542291026-7eec264c27ff'), rating: 4.9, reviews: 8640, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Salto 100mm', 'Studs Rockstud icônicos', 'Couro nappa', 'Forro em couro', 'Festa e eventos'], desc: 'Rockstud Pump 100mm Nude — Valentino.' },
    { id: 'm29', brand: 'Off-White', brandTier: 'griffe', category: 'Masculino', name: 'Hoodie Diag Arrow Preto', shop: 'Mercadopamina', price: 2890, oldPrice: 3400, tag: 'Griffe', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.4, reviews: 6537, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Moletom premium algodão', 'Estampa arrow diagonal', 'Capuz com cordão', 'Logo Off-White', 'Streetwear luxury'], desc: 'Hoodie Diag Arrow Preto — Off-White.' },
    { id: 'm30', brand: 'Supreme', brandTier: 'griffe', category: 'Masculino', name: 'Box Logo Tee FW24 Branco', shop: 'Mercadopamina', price: 1890, oldPrice: 2200, tag: 'Griffe', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.3, reviews: 10766, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Algodão pesado 100%', 'Box logo serigrafado', 'Edição limitada', 'Fit regular', 'Colecionável streetwear'], desc: 'Box Logo Tee FW24 Branco — Supreme.' },
    { id: 'm31', brand: 'Jordan', brandTier: 'premium', category: 'Calçados', name: 'Air Jordan 1 Retro High OG Chicago', shop: 'Mercadopamina', price: 1599, oldPrice: 1899, tag: 'Jordan', image: ecImg('photo-1542291026-7eec264c27ff'), rating: 4.4, reviews: 4552, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Cabedal couro premium', 'Swoosh e Wings clássicos', 'Entressola Air-Sole', 'Sola de borracha', 'Ícone basketball e street'], desc: 'Air Jordan 1 Retro High OG Chicago — Jordan.' },
    { id: 'm32', brand: 'Vans', brandTier: 'premium', category: 'Calçados', name: 'Old Skool Classic Preto/Branco', shop: 'Mercadopamina', price: 399, oldPrice: 499, tag: 'Vans', image: ecImg('photo-1600185365926-3a2ce3cdb9eb'), rating: 4.3, reviews: 11902, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Canvas e suede', 'Faixa lateral waffle', 'Solado vulcanizado waffle', 'Unissex atemporal', 'Skate e casual'], desc: 'Old Skool Classic Preto/Branco — Vans.' },
    { id: 'm33', brand: 'Converse', brandTier: 'premium', category: 'Calçados', name: 'Chuck 70 High Preto', shop: 'Mercadopamina', price: 449, oldPrice: 549, tag: 'Converse', image: ecImg('photo-1542291026-7eec264c27ff'), rating: 4.7, reviews: 8697, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Lona premium mais espessa', 'Solado de borracha vintage', 'Borracha foxing gloss', 'Palmilha OrthoLite', 'Clássico atemporal'], desc: 'Chuck 70 High Preto — Converse.' },
    { id: 'm34', brand: 'Crocs', brandTier: 'popular', category: 'Calçados', name: 'Classic Clog Preto', shop: 'Mercadopamina', price: 249, oldPrice: 299, tag: 'Crocs', image: ecImg('photo-1603487742874-03f67dfec1a3'), rating: 4.4, reviews: 11851, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Material Croslite leve', '13 furos ventilação', 'Jibbitz personalizável', 'Conforto o dia todo', 'Unissex'], desc: 'Classic Clog Preto — Crocs.' },
    { id: 'm35', brand: 'Birkenstock', brandTier: 'premium', category: 'Calçados', name: 'Arizona Birko-Flor Preto', shop: 'Mercadopamina', price: 449, oldPrice: 549, tag: 'Birkenstock', image: ecImg('photo-1603487742874-03f67dfec1a3'), rating: 4.8, reviews: 5757, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Duas tiras ajustáveis', 'Footbed anatômico cork-latex', 'Sola EVA flexível', 'Clássico alemão', 'Verão e casa'], desc: 'Arizona Birko-Flor Preto — Birkenstock.' },
    { id: 'm36', brand: 'Levi\'s', brandTier: 'premium', category: 'Masculino', name: '501 Original Fit Azul Escuro', shop: 'Mercadopamina', price: 399, oldPrice: 499, tag: 'Levi\'s', image: ecImg('photo-1624378439575-d8705ad7ae80'), rating: 4.6, reviews: 5702, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Corte original straight', 'Botão fly 501', 'Denim 100% algodão', '5 bolsos clássicos', 'Desde 1873'], desc: '501 Original Fit Azul Escuro — Levi\'s.' },
    { id: 'm37', brand: 'Tommy Hilfiger', brandTier: 'premium', category: 'Masculino', name: 'Camisa Slim Fit Azul', shop: 'Mercadopamina', price: 349, oldPrice: 449, tag: 'Tommy', image: ecImg('photo-1621072156002-e2fccdc0b176'), rating: 4.4, reviews: 5518, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Algodão oxford', 'Logo TH bordado', 'Gola button-down', 'Slim fit moderno', 'Trabalho e casual'], desc: 'Camisa Slim Fit Azul — Tommy Hilfiger.' },
    { id: 'm38', brand: 'Calvin Klein', brandTier: 'popular', category: 'Masculino', name: 'Pack 3 Boxer Cotton Pretas', shop: 'Mercadopamina', price: 199, oldPrice: 249, tag: 'CK', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.4, reviews: 3369, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Algodão com elastano', 'Cintura elástica logo CK', 'Pack econômico', 'Conforto diário', 'Básico premium'], desc: 'Pack 3 Boxer Cotton Pretas — Calvin Klein.' },
    { id: 'm39', brand: 'Victoria\'s Secret', brandTier: 'popular', category: 'Feminino', name: 'Body Splash Bare Vanilla 250ml', shop: 'Mercadopamina', price: 129, oldPrice: 169, tag: 'VS', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.7, reviews: 5381, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Fragrância baunilha suave', 'Camadas leves para o dia', '250ml spray corporal', 'Linha bestseller', 'Presente e uso diário'], desc: 'Body Splash Bare Vanilla 250ml — Victoria\'s Secret.' },
    { id: 'm40', brand: 'Natura', brandTier: 'popular', category: 'Feminino', name: 'Kit Tododia Ameixa 4 itens', shop: 'Mercadopamina', price: 89.9, oldPrice: 119.9, tag: 'Natura', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.3, reviews: 6520, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Sabonete líquido + hidratante', 'Desodorante colônia', 'Necessaire presenteável', 'Fragrância ameixa floral', 'Marca brasileira'], desc: 'Kit Tododia Ameixa 4 itens — Natura.' },
    { id: 'm41', brand: 'O Boticário', brandTier: 'premium', category: 'Masculino', name: 'Malbec Colônia 100ml', shop: 'Mercadopamina', price: 149, oldPrice: 189, tag: 'Boticário', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.6, reviews: 2728, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Notas amadeiradas especiadas', 'Linha masculina ícone BR', 'Fixação prolongada', '100ml spray', 'Presente clássico'], desc: 'Malbec Colônia 100ml — O Boticário.' },
    { id: 'm42', brand: 'Reserva', brandTier: 'premium', category: 'Masculino', name: 'Camisa Linho Manga Curta Bege', shop: 'Mercadopamina', price: 299, oldPrice: 399, tag: 'Reserva', image: ecImg('photo-1621072156002-e2fccdc0b176'), rating: 4.7, reviews: 5670, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['100% linho respirável', 'Manga curta verão', 'Botões madrepérola', 'Marca brasileira premium', 'Casual elegante'], desc: 'Camisa Linho Manga Curta Bege — Reserva.' },
    { id: 'm43', brand: 'Animale', brandTier: 'premium', category: 'Feminino', name: 'Blazer Alfaiataria Preto', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Animale', image: ecImg('photo-1591047139829-d91aecb6caea'), rating: 4.5, reviews: 9650, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Alfaiataria estruturada', 'Um botão moderno', 'Forro acetinado', 'Marca brasileira fashion', 'Trabalho e festa'], desc: 'Blazer Alfaiataria Preto — Animale.' },
    { id: 'm44', brand: 'Cantão', brandTier: 'premium', category: 'Feminino', name: 'Cardigan Tricot Mescla Cinza', shop: 'Mercadopamina', price: 449, oldPrice: 549, tag: 'Cantão', image: ecImg('photo-1591047139829-d91aecb6caea'), rating: 4.5, reviews: 6957, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Tricot macio mescla', 'Botões frontais', 'Bolso frontal', 'Conforto outono/inverno', 'Marca BR tradicional'], desc: 'Cardigan Tricot Mescla Cinza — Cantão.' },
    { id: 'm45', brand: 'Nike', brandTier: 'premium', category: 'Masculino', name: 'Dri-FIT Challenger Shorts 7"', shop: 'Mercadopamina', price: 199, oldPrice: 249, tag: 'Nike', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.6, reviews: 6525, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Tecido Dri-FIT respirável', 'Bolsos com zíper', '7 polegadas comprimento', 'Brief interno', 'Corrida e treino'], desc: 'Dri-FIT Challenger Shorts 7" — Nike.' },
    { id: 'm46', brand: 'Under Armour', brandTier: 'premium', category: 'Masculino', name: 'HeatGear Compression Preta', shop: 'Mercadopamina', price: 249, oldPrice: 299, tag: 'UA', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.6, reviews: 1657, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['HeatGear mantém fresco', 'Compressão segunda pele', 'Anti-odor technology', 'Secagem rápida', 'Academia e esporte'], desc: 'HeatGear Compression Preta — Under Armour.' },
    { id: 'm47', brand: 'Speedo', brandTier: 'premium', category: 'Feminino', name: 'Maiô Performance Preto', shop: 'Mercadopamina', price: 279, oldPrice: 349, tag: 'Speedo', image: ecImg('photo-1595777457583-95e059d581b8'), rating: 4.8, reviews: 8269, sizes: ['P', 'M', 'G', 'GG'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Tecido resistente cloro', 'Modelagem performance', 'Alças largas suporte', 'Marca referência natação', 'Piscina e praia'], desc: 'Maiô Performance Preto — Speedo.' },
    { id: 'm48', brand: 'Oakley', brandTier: 'premium', category: 'Acessórios', name: 'Holbrook Prizm Sapphire Polarizado', shop: 'Mercadopamina', price: 699, oldPrice: 849, tag: 'Oakley', image: ecImg('photo-1572635196237-14b3f281503f'), rating: 4.8, reviews: 2112, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Lentes Prizm polarizadas', 'Armação O Matter leve', 'Proteção UV400', 'Estilo surf/skate', 'Estojo incluso'], desc: 'Holbrook Prizm Sapphire Polarizado — Oakley.' },
    { id: 'm49', brand: 'Fossil', brandTier: 'premium', category: 'Acessórios', name: 'Relógio Grant Couro Marrom', shop: 'Mercadopamina', price: 899, oldPrice: 1099, tag: 'Fossil', image: ecImg('photo-1434493789847-2f02dc6ca35d'), rating: 4.6, reviews: 9212, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Mostrador romano', 'Pulseira couro genuíno', 'Quartz preciso', '50m resistência água', 'Casual elegante'], desc: 'Relógio Grant Couro Marrom — Fossil.' },
    { id: 'm50', brand: 'Pandora', brandTier: 'premium', category: 'Acessórios', name: 'Pulseira Moments + Charm Coração', shop: 'Mercadopamina', price: 599, oldPrice: 749, tag: 'Pandora', image: ecImg('photo-1611591437281-460bfbe1220a'), rating: 4.7, reviews: 6842, sizes: ['Único'], color: 'Variado', material: 'Premium', fit: 'Regular', care: 'Conforme etiqueta', specs: ['Prata esterlina 925', 'Fecho coração logo', 'Charm coração cravejado', 'Personalizável com charms', 'Presente romântico'], desc: 'Pulseira Moments + Charm Coração — Pandora.' },
  ];

  w.DOPAMINA_CATALOG_EXPAND = { premium: premium, fashion: fashion };
})(window);
