/** Catálogo — marcas reais, fotos de produto, preços BR, ficha técnica */
(function (w) {
  'use strict';

  function wikiThumb(path, width) {
    var file = path.split('/').pop();
    return 'https://upload.wikimedia.org/wikipedia/commons/thumb/' + path + '/' + width + 'px-' + file;
  }

  function wikiFile(path) {
    return 'https://upload.wikimedia.org/wikipedia/commons/' + path;
  }

  function unsplash(photoId) {
    return 'https://images.unsplash.com/' + photoId + '?w=720&h=720&fit=crop&q=90&auto=format';
  }

  function foodReviews(name) {
    return [
      { user: 'Camila R.', stars: 5, text: name + ' chegou quentinho e bem embalado. Porção fiel ao cardápio.', date: 'há 2 dias', verified: true },
      { user: 'Rafael M.', stars: 4, text: 'Sabor muito bom. Entrega levou uns 8 min a mais que o previsto, mas valeu.', date: 'há 5 dias', verified: true },
      { user: 'Ana Paula', stars: 5, text: 'Um dos melhores pedidos que fiz pelo app. Repetiria sem pensar.', date: 'há 1 semana', verified: true },
      { user: 'Bruno S.', stars: 3, text: 'Comida boa, mas veio sem o molho extra que marquei.', date: 'há 3 dias', verified: true },
      { user: 'Fernanda L.', stars: 4, text: 'Custo-benefício justo para a região. Embalagem segura.', date: 'há 2 semanas', verified: false },
    ];
  }

  function productReviews(name) {
    return [
      { user: 'Compra verificada', stars: 5, title: 'Produto conforme anunciado', text: name + ' chegou lacrado, dentro do prazo. Funcionando perfeitamente.', date: '18 jun 2026', helpful: 124 },
      { user: 'João V.', stars: 4, title: 'Bom custo-benefício', text: 'Atendeu expectativa. Embalagem original e nota fiscal.', date: '8 jun 2026', helpful: 56 },
      { user: 'Mariana K.', stars: 5, title: 'Recomendo', text: 'Entrega rápida. Produto original, sem avarias.', date: '1 jun 2026', helpful: 31 },
      { user: 'Carlos E.', stars: 3, title: 'Ok', text: 'Produto bom, mas peguei em promoção — fora dela o preço é salgado.', date: '25 mai 2026', helpful: 12 },
    ];
  }

  function fashionReviews(name, brand) {
    return [
      { user: 'Compra verificada', stars: 5, title: 'Original ' + brand, text: name + ' — etiqueta e acabamento conferem com a loja oficial.', date: '20 jun 2026', helpful: 89 },
      { user: 'Lívia M.', stars: 5, title: 'Caimento perfeito', text: 'Tecido de qualidade, igual às fotos. Chegou em 4 dias úteis.', date: '12 jun 2026', helpful: 44 },
      { user: 'Thiago A.', stars: 4, title: 'Boa compra', text: 'Produto bonito e bem embalado. Tamanho bateu com a tabela da marca.', date: '3 jun 2026', helpful: 21 },
    ];
  }

  var express = [
    { id: 'f01', brand: 'Burger King', name: 'WHOPPER® + Batata Média + Coca-Cola 500ml', shop: 'Burger King', price: 49.9, tag: 'Mais pedido', image: wikiThumb('8/85/Burger_King_Whopper.jpg', 800), rating: 4.7, reviews: 8420, delivery: '25–40 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 1.180 kcal', ingredients: ['Hambúrguer 113g chama grelhada', 'Batata média', 'Refrigerante 500ml'], desc: 'Combo clássico Burger King com sanduíche WHOPPER®, batata e Coca-Cola.' },
    { id: 'f02', brand: 'Pizza Hut', name: 'Pizza Grande Calabresa 35cm', shop: 'Pizza Hut', price: 74.9, tag: '35 cm', image: wikiThumb('a/a3/Pizza_Hut_Pizza.jpg', 800), rating: 4.6, reviews: 5230, delivery: '35–50 min', fee: 'R$ 5,99', portion: '2–3 pessoas', calories: '≈ 960 kcal/fatia', ingredients: ['Massa tradicional', 'Molho de tomate', 'Mussarela', 'Calabresa', 'Orégano'], desc: 'Pizza grande calabresa assada no forno Pizza Hut. Serve até 3 pessoas.' },
    { id: 'f03', brand: "McDonald's", name: 'McOferta Média Big Mac + McFritas + Coca-Cola', shop: "McDonald's", price: 39.9, tag: 'Combo', image: wikiThumb('4/4f/McDonald%27s_Big_Mac_hamburger.jpg', 800), rating: 4.5, reviews: 12400, delivery: '20–35 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 1.050 kcal', ingredients: ['Big Mac', 'McFritas média', 'Coca-Cola 400ml'], desc: 'Combo médio McDonald\'s com o sanduíche mais icônico do mundo.' },
    { id: 'f04', brand: 'KFC', name: 'Balde 8 Pedaços Original Recipe', shop: 'KFC', price: 54.9, tag: 'Balde', image: wikiThumb('2/2e/KFC_Original_Recipe_fried_chicken.jpg', 800), rating: 4.6, reviews: 3890, delivery: '30–45 min', fee: 'R$ 4,99', portion: '2–3 pessoas', calories: '≈ 2.400 kcal', ingredients: ['8 pedaços frango', 'Tempero Original Recipe 11 ervas'], desc: 'Balde família KFC com frango empanado crocante e receita secreta.' },
    { id: 'f05', brand: 'Subway', name: 'Sub 30cm Frango Defumado + Queijo', shop: 'Subway', price: 32.9, tag: 'Subway', image: wikiThumb('5/57/Subway_sandwich.jpg', 800), rating: 4.5, reviews: 6780, delivery: '20–35 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 520 kcal', ingredients: ['Pão italiano 30cm', 'Frango defumado', 'Queijo prato', 'Alface', 'Tomate'], desc: 'Subway 30cm montado na hora — opção mais pedida com frango defumado.' },
    { id: 'f06', brand: "Habib's", name: 'Esfiha Aberta de Carne — 12 unidades', shop: "Habib's", price: 29.9, tag: 'Árabe', image: wikiThumb('4/4e/Esfiha.jpg', 800), rating: 4.4, reviews: 15600, delivery: '25–40 min', fee: 'Grátis', portion: '2 pessoas', calories: '≈ 180 kcal/un', ingredients: ['Massa árabe', 'Carne temperada', 'Limão'], desc: 'Caixa com 12 esfihas abertas Habib\'s, quentinhas e bem recheadas.' },
    { id: 'f07', brand: "Bob's", name: 'Bob\'s Duplo + Batata + Refri', shop: "Bob's", price: 36.9, tag: 'Combo', image: wikiThumb('6/6e/Bobs_hamburger.jpg', 800), rating: 4.4, reviews: 9200, delivery: '25–40 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 980 kcal', ingredients: ['2 hambúrgueres 80g', 'Queijo cheddar', 'Batata', 'Refrigerante'], desc: 'Combo Bob\'s com duplo hambúrguer, batata crocante e bebida.' },
    { id: 'f08', brand: 'Starbucks', name: 'Frappuccino® Mocha 500ml', shop: 'Starbucks', price: 24.9, tag: 'Bebida', image: wikiThumb('5/5e/Frappuccino.jpg', 800), rating: 4.5, reviews: 3400, delivery: '20–35 min', fee: 'Grátis', portion: '500 ml', calories: '≈ 410 kcal', ingredients: ['Espresso', 'Leite', 'Chocolate', 'Gelo', 'Chantilly'], desc: 'Frappuccino Mocha gelado cremoso, 500ml, com café Starbucks.' },
    { id: 'f09', brand: 'Outback', name: 'Picanha na Chapa 400g + Arroz e Farofa', shop: 'Outback', price: 89.9, tag: 'Churrasco', image: wikiThumb('4/4f/Picanha_na_chapa.jpg', 800), rating: 4.8, reviews: 3800, delivery: '45–60 min', fee: 'R$ 6,99', portion: '1 pessoa', calories: '≈ 890 kcal', ingredients: ['Picanha 400g', 'Arroz', 'Farofa', 'Vinagrete'], desc: 'Prato executivo Outback com picanha grelhada no ponto.' },
    { id: 'f10', brand: 'Outback', name: 'Brownie Thunder com Sorvete', shop: 'Outback', price: 28.9, tag: 'Sobremesa', image: wikiThumb('9/9d/Brownie_with_ice_cream.jpg', 800), rating: 4.7, reviews: 2890, delivery: '35–50 min', fee: 'R$ 5,99', portion: '1–2 pessoas', calories: '≈ 620 kcal', ingredients: ['Brownie chocolate', 'Sorvete baunilha', 'Calda'], desc: 'Sobremesa clássica Outback — brownie quente com sorvete.' },
    { id: 'f11', brand: 'Giraffas', name: 'Picanha Light 200g + Arroz + Feijão', shop: 'Giraffas', price: 44.9, tag: 'Executivo', image: wikiThumb('3/3f/Plated_steak_with_rice_and_beans.jpg', 800), rating: 4.5, reviews: 5600, delivery: '30–45 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 720 kcal', ingredients: ['Picanha 200g', 'Arroz', 'Feijão', 'Farofa'], desc: 'Marmita executiva Giraffas com picanha grelhada e acompanhamentos.' },
    { id: 'f12', brand: 'Sushi Prime', name: 'Combo Sashimi e Sushi — 50 peças', shop: 'Sushi Prime', price: 109.9, tag: 'Premium', image: wikiThumb('6/60/Sushi_platter.jpg', 800), rating: 4.9, reviews: 4100, delivery: '40–55 min', fee: 'R$ 6,99', portion: '2–3 pessoas', calories: '≈ 850 kcal', ingredients: ['Salmão', 'Atum', 'Peixe branco', 'Arroz', 'Wasabi'], desc: 'Combinado premium para compartilhar com shoyu e gengibre.' },
    { id: 'f13', brand: 'Ramen Kuma', name: 'Ramen Tonkotsu Especial', shop: 'Ramen Kuma', price: 42.9, tag: 'Japonês', image: wikiThumb('9/94/Ramen_Tonkotsu.jpg', 800), rating: 4.8, reviews: 1890, delivery: '30–45 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 680 kcal', ingredients: ['Caldo tonkotsu 12h', 'Macarrão', 'Ovo mollet', 'Narutomaki'], desc: 'Ramen autêntico com caldo cremoso de osso de porco.' },
    { id: 'f14', brand: 'Açaí Concept', name: 'Açaí 700ml Nutella, Banana e Granola', shop: 'Açaí Concept', price: 39.9, tag: '700 ml', image: wikiThumb('7/7a/Acai_bowl_with_fruit.jpg', 800), rating: 4.8, reviews: 6200, delivery: '15–30 min', fee: 'Grátis', portion: '700 ml', calories: '≈ 540 kcal', ingredients: ['Açaí premium', 'Nutella', 'Banana', 'Granola'], desc: 'Copo 700ml montado na hora — best-seller da casa.' },
    { id: 'f15', brand: 'Domino\'s', name: 'Pizza Média Pepperoni + Borda Recheada', shop: 'Domino\'s Pizza', price: 59.9, tag: 'Pizza', image: wikiThumb('a/a3/Pizza_Hut_Pizza.jpg', 800), rating: 4.6, reviews: 8900, delivery: '30–45 min', fee: 'R$ 4,99', portion: '2 pessoas', calories: '≈ 880 kcal/fatia', ingredients: ['Massa fina', 'Pepperoni', 'Mussarela', 'Borda catupiry'], desc: 'Pizza média pepperoni Domino\'s com borda recheada de catupiry.' },
    { id: 'f16', brand: 'Empório do Salgado', name: 'Coxinha de Frango c/ Catupiry', shop: 'Empório do Salgado', price: 16.9, tag: 'Mais vendida', image: wikiThumb('8/8a/Coxinha_Brasil.jpg', 800), rating: 4.8, reviews: 8900, delivery: '15–25 min', fee: 'Grátis', portion: '1 unidade', calories: '≈ 280 kcal', ingredients: ['Frango desfiado', 'Catupiry', 'Massa de batata'], desc: 'Coxinha tradicional brasileira grande e bem recheada.' },
    { id: 'f17', brand: 'The Craft Burger', name: 'Smash Burger Duplo 2×90g', shop: 'The Craft Burger', price: 45.9, tag: 'Artesanal', image: wikiThumb('6/6d/Cheeseburger.jpg', 800), rating: 4.8, reviews: 1890, delivery: '30–45 min', fee: 'R$ 4,49', portion: '1 pessoa', calories: '≈ 920 kcal', ingredients: ['2 smash 90g', 'Pão brioche', 'Cheddar', 'Cebola caramelizada'], desc: 'Hambúrguer artesanal smash com duplo blend e queijo derretido.' },
    { id: 'f18', brand: 'Poke House', name: 'Poke Salmão Premium 400g', shop: 'Poke House', price: 54.9, tag: 'Saudável', image: wikiThumb('4/4e/Poke_bowl.jpg', 800), rating: 4.7, reviews: 1890, delivery: '25–40 min', fee: 'R$ 3,99', portion: '400 g', calories: '≈ 480 kcal', ingredients: ['Salmão fresco', 'Arroz japonês', 'Abacate', 'Edamame'], desc: 'Bowl poke montado na hora com salmão em cubos.' },
    { id: 'f19', brand: 'Cantina Nonna', name: 'Lasanha à Bolonhesa (serve 2)', shop: 'Cantina Nonna', price: 58.9, tag: 'Italiana', image: wikiThumb('b/ba/Lasagna_-_Freshly_baked.jpg', 800), rating: 4.7, reviews: 2450, delivery: '35–50 min', fee: 'Grátis', portion: '2 pessoas', calories: '≈ 760 kcal', ingredients: ['Massa fresca', 'Ragù bolonhesa', 'Bechamel', 'Parmesão'], desc: 'Lasanha gratinada italiana individual grande.' },
    { id: 'f20', brand: 'Taco Libre', name: 'Taco Box para 4 pessoas', shop: 'Taco Libre', price: 68.9, tag: 'Mexicano', image: wikiThumb('7/73/Tacos_de_carne_asada.jpg', 800), rating: 4.6, reviews: 1560, delivery: '30–45 min', fee: 'Grátis', portion: '4 pessoas', calories: '≈ 320 kcal/taco', ingredients: ['12 tacos', 'Carne', 'Guacamole', 'Pico de gallo'], desc: 'Box compartilhável estilo mexicano com molhos à parte.' },
    { id: 'f21', brand: 'Hot Dog Paulista', name: 'Hot Dog Completo Paulista', shop: 'Hot Dog Paulista', price: 27.9, tag: 'Clássico SP', image: wikiThumb('4/4c/Hot_dog_with_mustard.jpg', 800), rating: 4.4, reviews: 2100, delivery: '20–30 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 650 kcal', ingredients: ['Salsicha', 'Purê', 'Milho', 'Batata palha', 'Molhos'], desc: 'Hot dog estilo São Paulo caprichado e bem servido.' },
    { id: 'f22', brand: 'Pastel da Esquina', name: 'Caixa Pastel de Carne — 6 unidades', shop: 'Pastel da Esquina', price: 32.9, tag: 'Salgado', image: wikiThumb('9/9a/Pastel_brasileiro.jpg', 800), rating: 4.6, reviews: 2100, delivery: '20–35 min', fee: 'Grátis', portion: '6 unidades', calories: '≈ 220 kcal/un', ingredients: ['Massa crocante', 'Carne moída temperada'], desc: 'Pastéis fritos na hora, crocantes por fora.' },
    { id: 'f23', brand: 'Donuts Factory', name: 'Box Donuts — 6 sortidos', shop: 'Donuts Factory', price: 36.9, tag: 'Doce', image: wikiThumb('3/31/Doughnuts_in_a_box.jpg', 800), rating: 4.7, reviews: 1560, delivery: '20–30 min', fee: 'Grátis', portion: '6 unidades', calories: '≈ 260 kcal/un', ingredients: ['Donuts glaceados', 'Recheios variados'], desc: 'Kit com 6 donuts sortidos da vitrine do dia.' },
    { id: 'f24', brand: 'Café Mineiro', name: 'Pão de Queijo — 20 unidades', shop: 'Café Mineiro', price: 17.9, tag: 'Snack', image: wikiThumb('6/6b/Pao_de_queijo.jpg', 800), rating: 4.9, reviews: 4500, delivery: '15–25 min', fee: 'Grátis', portion: '20 unidades', calories: '≈ 80 kcal/un', ingredients: ['Polvilho', 'Queijo minas', 'Ovos'], desc: 'Pão de queijo mineiro assado, quentinho e macio.' },
    { id: 'f25', brand: 'Wok Express', name: 'Yakisoba de Carne 700g', shop: 'Wok Express', price: 41.9, tag: 'Oriental', image: wikiThumb('0/0a/Yakisoba.jpg', 800), rating: 4.6, reviews: 1780, delivery: '30–45 min', fee: 'Grátis', portion: '700 g', calories: '≈ 580 kcal', ingredients: ['Macarrão', 'Carne bovina', 'Legumes', 'Molho agridoce'], desc: 'Yakisoba bem servido para 1–2 pessoas.' },
    { id: 'f26', brand: 'Crêperie Paris 6', name: 'Crepe Nutella com Morangos', shop: 'Crêperie Paris 6', price: 26.9, tag: 'Doce', image: wikiThumb('1/1a/Crepes_with_Nutella_and_strawberries.jpg', 800), rating: 4.5, reviews: 780, delivery: '20–30 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 480 kcal', ingredients: ['Massa crepe', 'Nutella', 'Morangos frescos'], desc: 'Crepe doce francês servido quente com frutas.' },
    { id: 'f27', brand: 'Gelato Italiano', name: 'Casquinha 2 Bolas', shop: 'Gelato Italiano', price: 14.9, tag: 'Sobremesa', image: wikiThumb('2/2e/Ice_cream_cone.jpg', 800), rating: 4.5, reviews: 980, delivery: '10–20 min', fee: 'Grátis', portion: '2 bolas', calories: '≈ 280 kcal', ingredients: ['Sorvete artesanal', 'Casquinha crocante'], desc: 'Gelato italiano em casquinha — sabores do balcão.' },
    { id: 'f28', brand: 'Bubble Mix', name: 'Bubble Tea Taro 500ml', shop: 'Bubble Mix', price: 19.9, tag: 'Bebida', image: wikiThumb('9/9f/Bubble_tea_taro.jpg', 800), rating: 4.4, reviews: 920, delivery: '15–25 min', fee: 'Grátis', portion: '500 ml', calories: '≈ 350 kcal', ingredients: ['Chá', 'Taro', 'Leite', 'Pérolas tapioca'], desc: 'Bubble tea cremoso com pérolas de tapioca.' },
    { id: 'f29', brand: 'Pasta Fresca', name: 'Penne Quattro Formaggi', shop: 'Pasta Fresca', price: 44.9, tag: 'Cremoso', image: wikiThumb('9/91/Penne_quattro_formaggi.jpg', 800), rating: 4.7, reviews: 1670, delivery: '30–45 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 720 kcal', ingredients: ['Penne', 'Gorgonzola', 'Parmesão', 'Mussarela', 'Catupiry'], desc: 'Massa italiana ao molho quatro queijos, al dente.' },
    { id: 'f30', brand: 'Brunch & Co', name: 'Waffle Belga com Frutas e Maple', shop: 'Brunch & Co', price: 32.9, tag: 'Café', image: wikiThumb('3/3a/Waffles_with_strawberries.jpg', 800), rating: 4.5, reviews: 650, delivery: '20–30 min', fee: 'Grátis', portion: '1 pessoa', calories: '≈ 520 kcal', ingredients: ['Waffle belga', 'Maple syrup', 'Frutas vermelhas'], desc: 'Waffle crocante ideal para brunch de fim de semana.' },
  ];

  express.forEach(function (p) {
    p.reviewList = foodReviews(p.name);
    p.shopRating = (4.4 + Math.random() * 0.5).toFixed(1);
  });

  var premium = [
    { id: 'p01', brand: 'Apple', name: 'iPhone 16 Pro 256GB Titânio Natural', shop: 'AMAZOOM', price: 8999, oldPrice: 9999, tag: 'Lançamento', image: wikiFile('f/f5/IPhone_16_Pro_Max.png'), rating: 4.8, reviews: 2847, prime: true, specs: ['Tela 6,3" OLED ProMotion', 'Chip A18 Pro', 'Câmera 48MP Fusion', 'Titânio grau 5'], desc: 'iPhone 16 Pro Apple com chip A18 Pro, Action Button e gravação 4K Dolby Vision.' },
    { id: 'p02', brand: 'Apple', name: 'MacBook Air 13" M3 16GB 512GB', shop: 'AMAZOOM', price: 10999, oldPrice: 12499, tag: 'Apple', image: wikiThumb('1/1b/MacBook_Air_M3_2024.jpg', 800), rating: 4.9, reviews: 1203, prime: true, specs: ['Apple M3 8-core', '16GB memória unificada', '512GB SSD', 'Até 18h bateria'], desc: 'MacBook Air ultrafino Apple — produtividade e bateria de dia inteiro.' },
    { id: 'p03', brand: 'Sony', name: 'PlayStation 5 Slim 1TB', shop: 'AMAZOOM', price: 3999, oldPrice: 4499, tag: 'Games', image: wikiFile('1/1b/PlayStation_5_and_DualSense_with_transparent_background.png'), rating: 4.8, reviews: 4521, prime: true, specs: ['SSD 1TB', 'Ray tracing', 'DualSense incluso', '4K até 120fps'], desc: 'Console Sony PS5 Slim com SSD ultrarrápido e feedback háptico.' },
    { id: 'p04', brand: 'Samsung', name: 'Galaxy S24 Ultra 256GB', shop: 'AMAZOOM', price: 7499, oldPrice: 8499, tag: 'Android', image: wikiThumb('8/8e/Samsung_Galaxy_S24_Ultra_%28cropped%29.png', 800), rating: 4.7, reviews: 1890, prime: true, specs: ['S Pen integrada', 'Câmera 200MP', 'Galaxy AI', 'Tela 6,8" Dynamic AMOLED'], desc: 'Flagship Samsung com S Pen e inteligência artificial Galaxy AI.' },
    { id: 'p05', brand: 'Brastemp', name: 'Geladeira Frost Free Inverse 443L', shop: 'AMAZOOM', price: 4299, oldPrice: 4999, tag: 'Eletro', image: wikiThumb('9/9e/Refrigerator.jpg', 800), rating: 4.6, reviews: 678, prime: false, specs: ['443 litros', 'Inox', 'Frost free', 'Painel eletrônico'], desc: 'Geladeira Brastemp inverse com freezer embaixo e controle digital.' },
    { id: 'p06', brand: 'Samsung', name: 'Smart TV 55" Crystal UHD 4K CU8000', shop: 'AMAZOOM', price: 2499, oldPrice: 2999, tag: 'TV', image: wikiThumb('4/4d/Samsung_4K_UHD_TV.jpg', 800), rating: 4.7, reviews: 2890, prime: true, specs: ['55"', '4K UHD', 'HDR10+', 'Tizen OS'], desc: 'Smart TV Samsung 4K com apps de streaming e controle por voz.' },
    { id: 'p07', brand: 'Apple', name: 'AirPods Pro 2ª geração USB-C', shop: 'AMAZOOM', price: 1899, oldPrice: 2299, tag: 'Áudio', image: wikiThumb('3/3b/AirPods_Pro_2nd_generation.png', 800), rating: 4.8, reviews: 8340, prime: true, specs: ['ANC adaptativo', 'Áudio espacial', 'USB-C', 'IP54'], desc: 'Fones Apple com cancelamento de ruído e áudio espacial personalizado.' },
    { id: 'p08', brand: 'Nintendo', name: 'Switch OLED 64GB', shop: 'AMAZOOM', price: 2499, oldPrice: 2799, tag: 'Games', image: wikiThumb('8/8d/Nintendo-Switch-OLED-White-Flap-Open.jpg', 800), rating: 4.8, reviews: 3102, prime: true, specs: ['Tela OLED 7"', '64GB', 'Dock', 'Joy-Con'], desc: 'Nintendo Switch OLED — portátil e TV com tela vibrante.' },
    { id: 'p09', brand: 'Xiaomi', name: 'Robô Aspirador Vacuum S10', shop: 'AMAZOOM', price: 2199, oldPrice: 2599, tag: 'Casa', image: wikiThumb('c/c0/Robot_vacuum_cleaner.jpg', 800), rating: 4.5, reviews: 1567, prime: true, specs: ['Mapeamento LDS', 'App Mi Home', '4.000Pa', 'Autovazio'], desc: 'Robô aspirador Xiaomi com navegação a laser e app.' },
    { id: 'p10', brand: 'Nespresso', name: 'Cafeteira Vertuo Pop', shop: 'AMAZOOM', price: 699, oldPrice: 849, tag: 'Cozinha', image: wikiThumb('9/9a/Nespresso_Vertuo.jpg', 800), rating: 4.6, reviews: 2140, prime: true, specs: ['Cápsulas Vertuo', 'Compacta', 'Aquecimento 25s'], desc: 'Cafeteira Nespresso com extração centrífuga e crema generosa.' },
    { id: 'p11', brand: 'Apple', name: 'Apple Watch Series 10 GPS 46mm', shop: 'AMAZOOM', price: 4299, oldPrice: 4799, tag: 'Wearable', image: wikiThumb('1/1a/Apple_Watch_Series_10_46mm.jpg', 800), rating: 4.8, reviews: 1987, prime: true, specs: ['Tela wide-angle', 'GPS', 'Oxímetro', '50m água'], desc: 'Apple Watch com monitoramento avançado de saúde e fitness.' },
    { id: 'p12', brand: 'DJI', name: 'Mini 4 Pro Fly More Combo', shop: 'AMAZOOM', price: 6499, oldPrice: 7299, tag: 'Creator', image: wikiThumb('4/4d/DJI_Mini_3_drone.jpg', 800), rating: 4.7, reviews: 456, prime: false, specs: ['4K HDR', 'Detecção omnidirecional', '34 min voo', 'RC-N2'], desc: 'Drone DJI compacto com câmera 4K e sensores de obstáculos.' },
    { id: 'p13', brand: 'Lenovo', name: 'PC Gamer Ryzen 5 + RTX 4060 16GB', shop: 'AMAZOOM', price: 5999, oldPrice: 6999, tag: 'Gamer', image: wikiThumb('8/8e/Gaming_computer.jpg', 800), rating: 4.7, reviews: 534, prime: true, specs: ['RTX 4060 8GB', 'Ryzen 5', '16GB RAM', 'SSD 512GB'], desc: 'Desktop gamer Lenovo para 1080p/1440p em alta taxa de quadros.' },
    { id: 'p14', brand: 'Electrolux', name: 'Micro-ondas 34L MI41S', shop: 'AMAZOOM', price: 699, oldPrice: 849, tag: 'Cozinha', image: wikiThumb('2/2f/Microwave_oven.jpg', 800), rating: 4.5, reviews: 2103, prime: true, specs: ['34 litros', 'Painel integrado', '6 níveis potência'], desc: 'Micro-ondas Electrolux com descongelamento automático.' },
    { id: 'p15', brand: 'Mondial', name: 'Air Fryer Family AFN-40-RI 4L', shop: 'AMAZOOM', price: 349, oldPrice: 449, tag: 'Mais vendido', image: wikiThumb('9/9a/Air_fryer.jpg', 800), rating: 4.7, reviews: 12400, prime: true, specs: ['4 litros', 'Timer 60 min', 'Cesto antiaderente'], desc: 'Fritadeira Mondial sem óleo — best-seller Brasil.' },
    { id: 'p16', brand: 'Sony', name: 'WH-1000XM5 — Preto', shop: 'AMAZOOM', price: 1899, oldPrice: 2299, tag: 'Áudio', image: wikiThumb('1/1d/Sony_WH-1000XM5_%28cropped%29.png', 800), rating: 4.8, reviews: 5678, prime: true, specs: ['ANC líder', '30h bateria', 'Multipoint', 'LDAC'], desc: 'Headphone Sony over-ear com melhor cancelamento de ruído da categoria.' },
    { id: 'p17', brand: 'Apple', name: 'iPad 11" A16 Wi-Fi 256GB', shop: 'AMAZOOM', price: 4999, oldPrice: 5499, tag: 'Tablet', image: wikiThumb('9/9a/IPad_11th_generation.png', 800), rating: 4.8, reviews: 1432, prime: true, specs: ['Chip A16', '256GB', 'Liquid Retina', 'Apple Pencil'], desc: 'iPad Apple versátil para estudo, trabalho e entretenimento.' },
    { id: 'p18', brand: 'Canon', name: 'EOS R50 Kit RF-S18-45mm', shop: 'AMAZOOM', price: 5499, oldPrice: 6199, tag: 'Foto', image: wikiThumb('9/9f/Canon_EOS_R50.jpg', 800), rating: 4.7, reviews: 389, prime: false, specs: ['24,2MP APS-C', '4K 60p', 'Dual Pixel AF', 'Kit lente'], desc: 'Mirrorless Canon compacta para foto e vídeo 4K.' },
    { id: 'p19', brand: 'Samsung', name: 'Galaxy Watch 7 Bluetooth 44mm', shop: 'AMAZOOM', price: 1699, oldPrice: 1999, tag: 'Wearable', image: wikiThumb('8/8a/Samsung_Galaxy_Watch_7.jpg', 800), rating: 4.6, reviews: 2341, prime: true, specs: ['Wear OS', 'BioActive Sensor', 'GPS', 'Gorilla Glass'], desc: 'Smartwatch Samsung com monitoramento de sono e treino.' },
    { id: 'p20', brand: 'JBL', name: 'Flip 6 — Preta', shop: 'AMAZOOM', price: 599, oldPrice: 749, tag: 'Áudio', image: wikiThumb('a/a1/JBL_Flip_5.jpg', 800), rating: 4.7, reviews: 8450, prime: true, specs: ['IP67', '12h bateria', 'PartyBoost'], desc: 'Caixa JBL portátil à prova d\'água com graves potentes.' },
    { id: 'p21', brand: 'Logitech', name: 'MX Master 3S — Grafite', shop: 'AMAZOOM', price: 549, oldPrice: 699, tag: 'Periféricos', image: wikiThumb('5/5a/Logitech_MX_Master_3.png', 800), rating: 4.8, reviews: 6780, prime: true, specs: ['8.000 DPI', 'Scroll MagSpeed', 'USB-C', 'Multi-device'], desc: 'Mouse Logitech premium para produtividade e design.' },
    { id: 'p22', brand: 'Dyson', name: 'V15 Detect Absolute', shop: 'AMAZOOM', price: 4999, oldPrice: 5799, tag: 'Casa', image: wikiThumb('d/d1/Dyson_V15_Detect.jpg', 800), rating: 4.8, reviews: 1234, prime: true, specs: ['Laser dust detect', '240AW', '60 min autonomia', 'HEPA'], desc: 'Aspirador sem fio Dyson com laser que revela pó invisível.' },
    { id: 'p23', brand: 'Kindle', name: 'Kindle 11ª geração 16GB', shop: 'AMAZOOM', price: 499, oldPrice: 599, tag: 'Leitura', image: wikiThumb('9/9e/Amazon_Kindle_11th_generation.jpg', 800), rating: 4.7, reviews: 9870, prime: true, specs: ['Tela 6"', '16GB', 'Luz ajustável', 'Semanas de bateria'], desc: 'Leitor Amazon Kindle leve com tela antirreflexo.' },
    { id: 'p24', brand: 'LG', name: 'Monitor UltraGear 27" 144Hz IPS', shop: 'AMAZOOM', price: 1299, oldPrice: 1599, tag: 'Monitor', image: wikiThumb('9/9e/Computer_monitor.jpg', 800), rating: 4.7, reviews: 1567, prime: true, specs: ['27" IPS', '144Hz', '1ms', 'FreeSync'], desc: 'Monitor gamer LG com cores precisas e 144Hz.' },
    { id: 'p25', brand: 'Meta', name: 'Quest 3 128GB', shop: 'AMAZOOM', price: 4999, oldPrice: 5499, tag: 'VR', image: wikiThumb('8/8e/Meta_Quest_3_headset.png', 800), rating: 4.7, reviews: 1234, prime: true, specs: ['Mixed reality', 'Snapdragon XR2 Gen 2', '128GB'], desc: 'Headset Meta Quest 3 com pass-through colorido e jogos VR.' },
    { id: 'p26', brand: 'De\'Longhi', name: 'Dedica EC685 Espresso', shop: 'AMAZOOM', price: 1899, oldPrice: 2199, tag: 'Barista', image: wikiThumb('4/4e/Espresso_machine.jpg', 800), rating: 4.6, reviews: 678, prime: true, specs: ['15 bar', 'Vaporizador leite', 'Compacta', 'Portafiltro'], desc: 'Máquina De\'Longhi para espresso estilo cafeteria em casa.' },
    { id: 'p27', brand: 'LG', name: 'Smart TV 65" 4K UHD UR8750', shop: 'AMAZOOM', price: 3299, oldPrice: 3799, tag: 'TV', image: wikiThumb('4/4d/Samsung_4K_UHD_TV.jpg', 800), rating: 4.7, reviews: 1890, prime: true, specs: ['65"', '4K', 'webOS 24', 'HDR10'], desc: 'TV LG grande para sala com controle por voz e apps.' },
    { id: 'p28', brand: 'Philips', name: 'OneBlade Pro QP6550', shop: 'AMAZOOM', price: 399, oldPrice: 499, tag: 'Beleza', image: wikiThumb('8/8a/Electric_razor.jpg', 800), rating: 4.6, reviews: 4560, prime: true, specs: ['Bateria 120 min', '3 pentes', 'À prova d\'água'], desc: 'Aparador Philips híbrido para rosto e corpo.' },
    { id: 'p29', brand: 'Consul', name: 'Fogão 5 Bocas Mesa de Vidro', shop: 'AMAZOOM', price: 1299, oldPrice: 1499, tag: 'Eletro', image: wikiThumb('5/5e/Gas_stove.jpg', 800), rating: 4.5, reviews: 1432, prime: false, specs: ['5 bocas', 'Mesa vidro', 'Forno 86L', 'Acendimento auto'], desc: 'Fogão Consul com mesa de vidro temperado e timer.' },
    { id: 'p30', brand: 'Asus', name: 'ROG Strix G16 RTX 4060 i7', shop: 'AMAZOOM', price: 8999, oldPrice: 9999, tag: 'Notebook', image: wikiThumb('9/9e/Gaming_laptop.jpg', 800), rating: 4.7, reviews: 890, prime: true, specs: ['RTX 4060', 'Intel i7', '16GB', 'SSD 1TB', '165Hz'], desc: 'Notebook gamer Asus ROG com tela 165Hz e teclado RGB.' },
  ];

  premium.forEach(function (p) {
    p.reviewList = productReviews(p.name);
  });

  var fashion = [
    { id: 'm01', brand: 'Gucci', brandTier: 'griffe', category: 'Acessórios', name: 'Bolsa GG Marmont Matelassê Mini', shop: 'SHENIM', price: 8990, oldPrice: 10990, tag: 'Griffe', image: wikiThumb('4/4e/Gucci_GG_Marmont_bag.jpg', 800), rating: 4.9, reviews: 412, sizes: ['Único'], color: 'Preto', material: 'Couro matelassê', fit: 'Crossbody', care: 'Limpar com pano seco', desc: 'Bolsa icônica Gucci GG Marmont em couro matelassê com ferragem dourada.' },
    { id: 'm02', brand: 'Louis Vuitton', brandTier: 'griffe', category: 'Acessórios', name: 'Neverfull MM Monogram', shop: 'SHENIM', price: 12990, oldPrice: 14500, tag: 'Griffe', image: wikiThumb('6/67/Louis_Vuitton_Neverfull.jpg', 800), rating: 4.9, reviews: 890, sizes: ['Único'], color: 'Monograma', material: 'Canvas Monogram', fit: 'Tote', care: 'Evitar umidade prolongada', desc: 'Bolsa Louis Vuitton Neverfull MM — ícone de luxo desde 2007.' },
    { id: 'm03', brand: 'Chanel', brandTier: 'griffe', category: 'Acessórios', name: 'Classic Flap Média — Caviar Preto', shop: 'SHENIM', price: 38900, oldPrice: 42000, tag: 'Alta costura', image: wikiThumb('5/5e/Chanel_2.55_flap_bag.jpg', 800), rating: 5.0, reviews: 156, sizes: ['Único'], color: 'Preto', material: 'Couro caviar', fit: 'Ombro/crossbody', care: 'Guardar com papel manteiga', desc: 'Classic Flap Chanel com corrente dourada e fecho CC — peça de investimento.' },
    { id: 'm04', brand: 'Balenciaga', brandTier: 'griffe', category: 'Calçados', name: 'Triple S Sneaker — Branco/Preto', shop: 'SHENIM', price: 6990, oldPrice: 8200, tag: 'Griffe', image: wikiThumb('8/8d/Balenciaga_Triple_S.jpg', 800), rating: 4.7, reviews: 678, sizes: ['38', '39', '40', '41', '42'], color: 'Branco/Preto', material: 'Couro/mesh', fit: 'Chunky — número normal', care: 'Escova macia', desc: 'Tênis Balenciaga Triple S que definiu o movimento chunky sneaker.' },
    { id: 'm05', brand: 'Prada', brandTier: 'griffe', category: 'Calçados', name: 'America\'s Cup Sneaker', shop: 'SHENIM', price: 5490, oldPrice: 6200, tag: 'Griffe', image: wikiThumb('3/3a/Prada_sneakers.jpg', 800), rating: 4.8, reviews: 234, sizes: ['37', '38', '39', '40', '41'], color: 'Branco', material: 'Couro e mesh', fit: 'Fiel ao tamanho', care: 'Impermeabilizar', desc: 'Sneaker Prada America\'s Cup com triângulo icônico lateral.' },
    { id: 'm06', brand: 'Versace', brandTier: 'griffe', category: 'Acessórios', name: 'Óculos Medusa Biggie — Dourado', shop: 'SHENIM', price: 2490, oldPrice: 3100, tag: 'Griffe', image: wikiThumb('5/5a/Sunglasses.jpg', 800), rating: 4.6, reviews: 189, sizes: ['Único'], color: 'Dourado', material: 'Metal acetato', fit: 'Unissex', care: 'Estojo rígido incluso', desc: 'Óculos Versace com detalhe Medusa e lentes UV400.' },
    { id: 'm07', brand: 'Nike', brandTier: 'premium', category: 'Calçados', name: 'Air Max 90 Essential — Branco', shop: 'SHENIM', price: 799, oldPrice: 999, tag: 'Nike', image: wikiThumb('3/37/Nike_Air_Max_90.png', 800), rating: 4.8, reviews: 12400, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Branco/Cinza', material: 'Couro e mesh', fit: 'Fiel ao tamanho', care: 'Limpar com escova úmida', desc: 'Nike Air Max 90 — clássico de 1990 com amortecimento Air visível.' },
    { id: 'm08', brand: 'Adidas', brandTier: 'premium', category: 'Calçados', name: 'Ultraboost 22 — Core Black', shop: 'SHENIM', price: 899, oldPrice: 1199, tag: 'Adidas', image: wikiThumb('5/57/Adidas_Ultra_Boost_4.0.jpg', 800), rating: 4.7, reviews: 8900, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Preto', material: 'Primeknit + Boost', fit: 'Ajuste sock-like', care: 'Lavar à mão', desc: 'Adidas Ultraboost com solado Boost para corrida e lifestyle.' },
    { id: 'm09', brand: 'New Balance', brandTier: 'premium', category: 'Calçados', name: '550 Branco/Verde', shop: 'SHENIM', price: 699, oldPrice: 899, tag: 'NB', image: wikiThumb('4/4e/New_Balance_550.jpg', 800), rating: 4.7, reviews: 5600, sizes: ['36', '37', '38', '39', '40', '41'], color: 'Branco/Verde', material: 'Couro sintético', fit: 'Número normal', care: 'Pano úmido', desc: 'New Balance 550 retro basketball — viral no streetwear.' },
    { id: 'm10', brand: 'Zara', brandTier: 'premium', category: 'Feminino', name: 'Trench Coat Oversized Bege', shop: 'SHENIM', price: 499, oldPrice: 699, tag: 'Zara', image: wikiThumb('9/9e/Trench_coat.jpg', 800), rating: 4.6, reviews: 3400, sizes: ['P', 'M', 'G'], color: 'Bege', material: 'Algodão poliéster', fit: 'Oversized', care: 'Lavar a seco', desc: 'Trench coat Zara oversized — peça-chave de guarda-roupa cápsula.' },
    { id: 'm11', brand: 'Mango', brandTier: 'premium', category: 'Feminino', name: 'Vestido Midi Satinado Preto', shop: 'SHENIM', price: 349, oldPrice: 499, tag: 'Mango', image: wikiThumb('6/6e/Black_dress.jpg', 800), rating: 4.7, reviews: 2100, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Poliéster acetinado', fit: 'Regular', care: 'Lavar à mão', desc: 'Vestido Mango midi com brilho satinado para festas e jantares.' },
    { id: 'm12', brand: 'Lacoste', brandTier: 'premium', category: 'Masculino', name: 'Polo Classic Fit — Branco', shop: 'SHENIM', price: 449, oldPrice: 599, tag: 'Lacoste', image: wikiThumb('2/2e/Lacoste_polo_shirt.jpg', 800), rating: 4.8, reviews: 6700, sizes: ['P', 'M', 'G', 'GG'], color: 'Branco', material: 'Algodão piquet', fit: 'Classic fit', care: 'Máq. 30°C', desc: 'Polo Lacoste com crocodilo bordado — ícone francês desde 1933.' },
    { id: 'm13', brand: 'H&M', brandTier: 'popular', category: 'Feminino', name: 'Camiseta Algodão Premium Branca', shop: 'SHENIM', price: 59.9, oldPrice: 79.9, tag: 'H&M', image: wikiThumb('2/2f/White_T-shirt.jpg', 800), rating: 4.5, reviews: 18900, sizes: ['P', 'M', 'G', 'GG'], color: 'Branco', material: '100% algodão', fit: 'Regular', care: 'Máq. 40°C', desc: 'Camiseta básica H&M em algodão premium — essencial do guarda-roupa.' },
    { id: 'm14', brand: 'Renner', brandTier: 'popular', category: 'Feminino', name: 'Calça Jeans Wide Leg Azul Médio', shop: 'SHENIM', price: 129.9, oldPrice: 179.9, tag: 'Renner', image: wikiThumb('4/4c/Blue_jeans.jpg', 800), rating: 4.6, reviews: 8900, sizes: ['36', '38', '40', '42', '44'], color: 'Azul médio', material: 'Algodão elastano', fit: 'Wide leg cintura alta', care: 'Lavar do avesso', desc: 'Jeans Renner wide leg tendência — confortável e versátil.' },
    { id: 'm15', brand: 'C&A', brandTier: 'popular', category: 'Feminino', name: 'Blusa Manga Longa Ribana', shop: 'SHENIM', price: 69.9, oldPrice: 99.9, tag: 'C&A', image: wikiThumb('8/8a/Long_sleeve_shirt.jpg', 800), rating: 4.4, reviews: 5600, sizes: ['P', 'M', 'G'], color: 'Nude', material: 'Viscose elastano', fit: 'Ajustada', care: 'Máq. delicado', desc: 'Blusa C&A em ribana macia — segunda pele para o dia a dia.' },
    { id: 'm16', brand: 'Riachuelo', brandTier: 'popular', category: 'Calçados', name: 'Sandália Flat Metalizada Dourada', shop: 'SHENIM', price: 79.9, oldPrice: 119.9, tag: 'Riachuelo', image: wikiThumb('5/5e/Sandals.jpg', 800), rating: 4.3, reviews: 4200, sizes: ['35', '36', '37', '38', '39'], color: 'Dourado', material: 'Sintético', fit: 'Fiel', care: 'Pano seco', desc: 'Sandália Riachuelo flat metalizada para o verão brasileiro.' },
    { id: 'm17', brand: 'Farm', brandTier: 'premium', category: 'Feminino', name: 'Vestido Estampa Tropical', shop: 'SHENIM', price: 389, oldPrice: 499, tag: 'Farm', image: wikiThumb('7/7a/Summer_dress.jpg', 800), rating: 4.8, reviews: 1890, sizes: ['P', 'M', 'G'], color: 'Multicolor', material: 'Viscose', fit: 'Fluido', care: 'Máq. delicado', desc: 'Vestido Farm com estampa exclusiva brasileira — marca carioca icônica.' },
    { id: 'm18', brand: 'Melissa', brandTier: 'popular', category: 'Calçados', name: 'Possession — Rosa Glitter', shop: 'SHENIM', price: 199, oldPrice: 249, tag: 'Melissa', image: wikiThumb('6/6e/Melissa_sandals.jpg', 800), rating: 4.7, reviews: 7800, sizes: ['35', '36', '37', '38', '39', '40'], color: 'Rosa glitter', material: 'Melflex', fit: 'Fiel', care: 'Água e sabão', desc: 'Sandália Melissa Possession — cheiro característico e conforto.' },
    { id: 'm19', brand: 'Shoulder', brandTier: 'premium', category: 'Feminino', name: 'Cropped Tricot Off-White', shop: 'SHENIM', price: 299, oldPrice: 399, tag: 'Shoulder', image: wikiThumb('9/9a/Crop_top.jpg', 800), rating: 4.6, reviews: 1200, sizes: ['P', 'M', 'G'], color: 'Off-white', material: 'Tricot algodão', fit: 'Cropped', care: 'Lavar à mão', desc: 'Cropped Shoulder em tricot — marca brasileira premium contemporânea.' },
    { id: 'm20', brand: 'Marisa', brandTier: 'popular', category: 'Feminino', name: 'Sutiã Conforto Microfibra', shop: 'SHENIM', price: 49.9, oldPrice: 69.9, tag: 'Marisa', image: wikiThumb('3/3a/Bra_lingerie.jpg', 800), rating: 4.4, reviews: 6700, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Microfibra', fit: 'Conforto sem aro', care: 'Máq. delicado', desc: 'Sutiã Marisa microfibra sem costura — conforto para o dia a dia.' },
    { id: 'm21', brand: 'Puma', brandTier: 'premium', category: 'Masculino', name: 'Camisa Palmeiras I 2025 Torcedor', shop: 'SHENIM', price: 349, oldPrice: 399, tag: 'Puma', image: wikiThumb('4/4f/Football_jersey.jpg', 800), rating: 4.8, reviews: 4500, sizes: ['P', 'M', 'G', 'GG'], color: 'Verde', material: 'Poliéster dry-fit', fit: 'Torcedor', care: 'Não usar alvejante', desc: 'Camisa oficial Puma Palmeiras temporada 2025 — torcedor.' },
    { id: 'm22', brand: 'Ray-Ban', brandTier: 'premium', category: 'Acessórios', name: 'Aviador Classic RB3025 — Dourado', shop: 'SHENIM', price: 699, oldPrice: 849, tag: 'Ray-Ban', image: wikiThumb('5/5a/Sunglasses.jpg', 800), rating: 4.8, reviews: 9200, sizes: ['Único'], color: 'Dourado/Verde G-15', material: 'Metal', fit: 'Unissex', care: 'Estojo + flanela', desc: 'Ray-Ban Aviador RB3025 — modelo usado por pilotos desde 1937.' },
    { id: 'm23', brand: 'Havaianas', brandTier: 'popular', category: 'Calçados', name: 'Top Brasil — Azul Naval', shop: 'SHENIM', price: 39.9, oldPrice: 49.9, tag: 'Havaianas', image: wikiThumb('6/6d/Havaianas_flip_flops.jpg', 800), rating: 4.9, reviews: 23400, sizes: ['35/36', '37/38', '39/40', '41/42'], color: 'Azul naval', material: 'Borracha', fit: 'Fiel', care: 'Lavar água fria', desc: 'Havaianas Top Brasil — chinelo mais vendido do país.' },
    { id: 'm24', brand: 'Colcci', brandTier: 'premium', category: 'Masculino', name: 'Camiseta Logo Bordado Preta', shop: 'SHENIM', price: 159, oldPrice: 199, tag: 'Colcci', image: wikiThumb('2/2f/Black_T-shirt.jpg', 800), rating: 4.5, reviews: 2100, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Algodão premium', fit: 'Slim', care: 'Máq. 30°C do avesso', desc: 'Camiseta Colcci com logo bordado — streetwear brasileiro premium.' },
  ];

  fashion.forEach(function (p) {
    p.reviewList = fashionReviews(p.name, p.brand);
    p.specs = [
      'Marca: ' + p.brand,
      'Cor: ' + p.color,
      'Material: ' + p.material,
      'Caimento: ' + p.fit,
      'Cuidados: ' + p.care,
    ];
  });

  w.DOPAMINA_CATALOG = { express: express, premium: premium, fashion: fashion };
})(window);
