/** Catálogo Dopamina — 30 comidas + 30 eletrônicos */
export const CATALOG = {
  express: [
    { id: 'f01', name: 'X-Tudo Supremo 4 Carnes', shop: 'Burger Dopamina', price: 42.9, emoji: '🍔', tag: 'Mais pedido' },
    { id: 'f02', name: 'Pizza 8 Queijos Colossal', shop: 'Pizza Neurônio', price: 89.9, emoji: '🍕', tag: '32 fatias' },
    { id: 'f03', name: 'Combo Whopper da Mente', shop: 'Rei do Fake', price: 54.9, emoji: '🍟', tag: 'Combo' },
    { id: 'f04', name: 'Bucket 20 Asinhas Picantes', shop: 'Frango Dopamina', price: 69.9, emoji: '🍗', tag: 'Picante' },
    { id: 'f05', name: 'Ramen Instantâneo Gourmet', shop: 'Tokyo Fake', price: 38.5, emoji: '🍜', tag: 'Quente' },
    { id: 'f06', name: 'Açaí 2L com Nutella', shop: 'Açaí do Paraíso', price: 45.0, emoji: '🫐', tag: 'Gigante' },
    { id: 'f07', name: 'Hot Dog Triplo Chicago', shop: 'Dog Mentiroso', price: 29.9, emoji: '🌭', tag: 'Clássico' },
    { id: 'f08', name: 'Sushi Combo 60 peças', shop: 'Sushi Imaginário', price: 119.9, emoji: '🍣', tag: 'Premium' },
    { id: 'f09', name: 'Taco Box para 4', shop: 'El Dopamina', price: 72.0, emoji: '🌮', tag: 'Mexicano' },
    { id: 'f10', name: 'Brownie com Sorvete 3 Bolas', shop: 'Doce Ilusão', price: 32.9, emoji: '🍫', tag: 'Sobremesa' },
    { id: 'f11', name: 'Milk-shake Oreo 700ml', shop: 'Shake da Fé', price: 24.9, emoji: '🥤', tag: 'Gelado' },
    { id: 'f12', name: 'Poke Bowl Salmão Extra', shop: 'Havai Fake', price: 58.9, emoji: '🥗', tag: 'Fit fake' },
    { id: 'f13', name: 'Lasanha Bolonhesa Família', shop: 'Nonna Dopamina', price: 64.9, emoji: '🍝', tag: 'Italiano' },
    { id: 'f14', name: 'Crepe Nutella com Morango', shop: 'Crepe Paris', price: 28.9, emoji: '🥞', tag: 'Doce' },
    { id: 'f15', name: 'Churrasco Misto 1kg', shop: 'Grill Imaginário', price: 98.0, emoji: '🥩', tag: 'Churras' },
    { id: 'f16', name: 'Pastel de Feira 6 unidades', shop: 'Feira Fake', price: 36.0, emoji: '🥟', tag: 'Tradicional' },
    { id: 'f17', name: 'Coxinha Premium Catupiry', shop: 'Salgados do Zé', price: 18.9, emoji: '🍗', tag: 'Salgado' },
    { id: 'f18', name: 'Waffle Belga com Calda', shop: 'Brunch Fake', price: 34.9, emoji: '🧇', tag: 'Café' },
    { id: 'f19', name: 'Espetinho Mix 5 palitos', shop: 'Espeto Dourado', price: 41.0, emoji: '🍢', tag: 'Boteco' },
    { id: 'f20', name: 'Macarrão 4 Queijos', shop: 'Pasta Dopamina', price: 47.9, emoji: '🧀', tag: 'Cremoso' },
    { id: 'f21', name: 'Bubble Tea Taro Grande', shop: 'Boba Fake', price: 22.9, emoji: '🧋', tag: 'Trend' },
    { id: 'f22', name: 'Tapioca de Carne Seca', shop: 'Nordeste Fake', price: 26.9, emoji: '🫓', tag: 'Regional' },
    { id: 'f23', name: 'Donuts Kit 6 Sabores', shop: 'Donut Neurônio', price: 39.9, emoji: '🍩', tag: 'Doce' },
    { id: 'f24', name: 'Frango Frito Bucket XL', shop: 'KFC Imaginário', price: 59.9, emoji: '🍗', tag: 'Crocante' },
    { id: 'f25', name: 'Pão de Queijo 20un', shop: 'Mineiro Fake', price: 19.9, emoji: '🧀', tag: 'Snack' },
    { id: 'f26', name: 'Hambúrguer Artesanal Duplo', shop: 'Craft Burger', price: 48.9, emoji: '🍔', tag: 'Artesanal' },
    { id: 'f27', name: 'Sorvete Casquinha 3 Sabores', shop: 'Gelato Fake', price: 16.9, emoji: '🍦', tag: 'Gelado' },
    { id: 'f28', name: 'Yakisoba Especial 800g', shop: 'China Fake', price: 44.9, emoji: '🥡', tag: 'Oriental' },
    { id: 'f29', name: 'Calzone Recheado Gigante', shop: 'Pizza Neurônio', price: 52.9, emoji: '🥟', tag: 'Forno' },
    { id: 'f30', name: 'Torta de Limão Fatia Dupla', shop: 'Doce Ilusão', price: 21.9, emoji: '🥧', tag: 'Sobremesa' },
  ],
  premium: [
    { id: 'p01', name: 'iPhone 16 Pro Max 1TB', shop: 'Dopamina Tech', price: 12999.0, emoji: '📱', tag: 'Lançamento' },
    { id: 'p02', name: 'MacBook Pro M4 Max 64GB', shop: 'Dopamina Tech', price: 28999.0, emoji: '💻', tag: 'Pro' },
    { id: 'p03', name: 'PlayStation 5 Pro + 2 Jogos', shop: 'Game Fake', price: 5499.0, emoji: '🎮', tag: 'Gamer' },
    { id: 'p04', name: 'Samsung Galaxy S25 Ultra', shop: 'Dopamina Tech', price: 8999.0, emoji: '📱', tag: 'Android' },
    { id: 'p05', name: 'Geladeira Smart French Door', shop: 'Eletro Dopamina', price: 12499.0, emoji: '🧊', tag: 'Smart' },
    { id: 'p06', name: 'TV OLED 85" 8K', shop: 'Vision Fake', price: 32999.0, emoji: '📺', tag: 'Cinema' },
    { id: 'p07', name: 'AirPods Max Titanium', shop: 'Dopamina Tech', price: 6999.0, emoji: '🎧', tag: 'Áudio' },
    { id: 'p08', name: 'Nintendo Switch 2 Bundle', shop: 'Game Fake', price: 4299.0, emoji: '🕹️', tag: 'Portátil' },
    { id: 'p09', name: 'Robô Aspirador Laser AI', shop: 'Casa Inteligente', price: 3899.0, emoji: '🤖', tag: 'Casa' },
    { id: 'p10', name: 'Máquina de Café Barista Pro', shop: 'Casa Inteligente', price: 4599.0, emoji: '☕', tag: 'Premium' },
    { id: 'p11', name: 'Apple Watch Ultra 3', shop: 'Dopamina Tech', price: 9999.0, emoji: '⌚', tag: 'Wearable' },
    { id: 'p12', name: 'Drone 8K Cinematic Pro', shop: 'Vision Fake', price: 15999.0, emoji: '🚁', tag: 'Creator' },
    { id: 'p13', name: 'Setup Gamer RTX 5090 Completo', shop: 'Game Fake', price: 45999.0, emoji: '🖥️', tag: 'Beast' },
    { id: 'p14', name: 'Micro-ondas Inverter 40L', shop: 'Eletro Dopamina', price: 1899.0, emoji: '📦', tag: 'Cozinha' },
    { id: 'p15', name: 'Air Fryer XXL 10L Digital', shop: 'Eletro Dopamina', price: 899.0, emoji: '🍳', tag: 'Trend' },
    { id: 'p16', name: 'Lava-louças 16 Serviços', shop: 'Eletro Dopamina', price: 5499.0, emoji: '🫧', tag: 'Casa' },
    { id: 'p17', name: 'Fone Sony WH-1000XM6', shop: 'Dopamina Tech', price: 2499.0, emoji: '🎧', tag: 'ANC' },
    { id: 'p18', name: 'iPad Pro 13" M4 2TB', shop: 'Dopamina Tech', price: 18999.0, emoji: '📲', tag: 'Tablet' },
    { id: 'p19', name: 'Câmera Mirrorless Full Frame', shop: 'Vision Fake', price: 21999.0, emoji: '📷', tag: 'Foto' },
    { id: 'p20', name: 'Smartwatch Galaxy Ultra', shop: 'Dopamina Tech', price: 3999.0, emoji: '⌚', tag: 'Fitness' },
    { id: 'p21', name: 'Purificador de Ar HEPA Pro', shop: 'Casa Inteligente', price: 2799.0, emoji: '💨', tag: 'Saúde' },
    { id: 'p22', name: 'Notebook Gamer 240Hz', shop: 'Game Fake', price: 12999.0, emoji: '💻', tag: '240Hz' },
    { id: 'p23', name: 'Caixa de Som JBL Party 320', shop: 'Dopamina Tech', price: 3299.0, emoji: '🔊', tag: 'Festa' },
    { id: 'p24', name: 'Fogão 5 Bocas com Forno AI', shop: 'Eletro Dopamina', price: 4299.0, emoji: '🔥', tag: 'Cozinha' },
    { id: 'p25', name: 'Kindle Scribe Premium', shop: 'Dopamina Tech', price: 2199.0, emoji: '📚', tag: 'Leitura' },
    { id: 'p26', name: 'Monitor Ultrawide 49" Curvo', shop: 'Game Fake', price: 8999.0, emoji: '🖥️', tag: 'Ultrawide' },
    { id: 'p27', name: 'Secadora de Roupas Heat Pump', shop: 'Eletro Dopamina', price: 6799.0, emoji: '👕', tag: 'Lavanderia' },
    { id: 'p28', name: 'Meta Quest 4 Pro 512GB', shop: 'Game Fake', price: 7499.0, emoji: '🥽', tag: 'VR' },
    { id: 'p29', name: 'Cafeteira Expresso Automática', shop: 'Casa Inteligente', price: 5999.0, emoji: '☕', tag: 'Barista' },
    { id: 'p30', name: 'Smart TV QLED 65" Gaming', shop: 'Vision Fake', price: 6499.0, emoji: '📺', tag: '120Hz' },
  ],
};

export function getProduct(id) {
  return [...CATALOG.express, ...CATALOG.premium].find((p) => p.id === id);
}

export function isExpress(id) {
  return id.startsWith('f');
}
