/** Catálogo — marcas reais, fotos de produto, preços BR, ficha técnica */
(function (w) {
  'use strict';

  function wikiThumb(path, width) {
    var file = path.split('/').pop();
    return 'https://upload.wikimedia.org/wikipedia/commons/thumb/' + path + '/' + width + 'px-' + file;
  }

  function wikiFile(path) {
    return 'https://upload.wikimedia.org/wikipedia/commons/' + path;
  }

  function unsplash(photoId) {
    return 'https://images.unsplash.com/' + photoId + '?w=800&h=800&fit=crop&fm=jpg&q=92&auto=format';
  }

  /** Foto packshot estilo marketplace (fundo claro, produto centralizado) */
  function ecImg(photoId) {
    return unsplash(photoId);
  }

  function productReviews(name) {
    return [
      { user: 'Compra verificada', stars: 5, title: 'Produto conforme anunciado', text: name + ' chegou lacrado, dentro do prazo. Funcionando perfeitamente.', date: '18 jun 2026', helpful: 124 },
      { user: 'João V.', stars: 4, title: 'Bom custo-benefício', text: 'Atendeu expectativa. Embalagem original e nota fiscal.', date: '8 jun 2026', helpful: 56 },
      { user: 'Mariana K.', stars: 5, title: 'Recomendo', text: 'Entrega rápida. Produto original, sem avarias.', date: '1 jun 2026', helpful: 31 },
      { user: 'Carlos E.', stars: 3, title: 'Ok', text: 'Produto bom, mas peguei em promoção — fora dela o preço é salgado.', date: '25 mai 2026', helpful: 12 },
    ];
  }

  function fashionReviews(name, brand) {
    return [
      { user: 'Compra verificada', stars: 5, title: 'Original ' + brand, text: name + ' — etiqueta e acabamento conferem com a loja oficial.', date: '20 jun 2026', helpful: 89 },
      { user: 'Lívia M.', stars: 5, title: 'Caimento perfeito', text: 'Tecido de qualidade, igual às fotos. Chegou em 4 dias úteis.', date: '12 jun 2026', helpful: 44 },
      { user: 'Thiago A.', stars: 4, title: 'Boa compra', text: 'Produto bonito e bem embalado. Tamanho bateu com a tabela da marca.', date: '3 jun 2026', helpful: 21 },
    ];
  }

  /* Comida / delivery — desativado (ver branch futuro) */
  var express = [];

  var premium = [
    { id: 'p01', brand: 'Apple', name: 'iPhone 16 Pro 256GB Titânio Natural',     shop: 'Mercadopamina', price: 8999, oldPrice: 9999, tag: 'Lançamento', image: ecImg('photo-1695048133144-6b33fd7b28b5'), rating: 4.8, reviews: 2847, prime: true, specs: ['Tela 6,3" Super Retina XDR OLED 120Hz', 'Chip Apple A18 Pro · Neural Engine 16-core', 'Câmera 48MP principal · zoom óptico 5x', 'USB-C · Wi-Fi 6E · Bluetooth 5.3 · 5G', 'Resistente a água IP68 · titânio grau 5'], desc: 'iPhone 16 Pro com tela ProMotion, chip A18 Pro e sistema de câmeras profissional — desempenho de ponta para foto, vídeo e jogos.' },
    { id: 'p02', brand: 'Apple', name: 'MacBook Air 13" M3 16GB 512GB',     shop: 'Mercadopamina', price: 10999, oldPrice: 12499, tag: 'Apple', image: ecImg('photo-1517336714731-489689fd1ca8'), rating: 4.9, reviews: 1203, prime: true, specs: ['Chip Apple M3 8-core CPU · GPU 10-core', '16GB memória unificada · SSD 512GB', 'Tela Liquid Retina 13,6" · 500 nits · P3', 'Até 18h de bateria · carregador MagSafe USB-C', 'MagSafe · 2× Thunderbolt · Touch ID · macOS'], desc: 'MacBook Air 13" com chip M3 — ultrafino, silencioso e com bateria para o dia inteiro de trabalho, estudo e criação.' },
    { id: 'p03', brand: 'Sony', name: 'PlayStation 5 Slim 1TB',     shop: 'Mercadopamina', price: 3999, oldPrice: 4499, tag: 'Games', image: ecImg('photo-1606813907291-d86efa9b94db'), rating: 4.8, reviews: 4521, prime: true, specs: ['SSD customizado 1TB — carregamento instantâneo', 'Ray tracing em tempo real · 4K até 120fps', 'Controle DualSense com feedback háptico e gatilhos adaptativos', 'Áudio 3D Tempest · compatível com jogos PS4', 'Design Slim compacto — cabe em qualquer setup'], desc: 'PlayStation 5 Slim 1TB com gráficos de nova geração, SSD ultrarrápido e DualSense para uma experiência imersiva em 4K.' },
    { id: 'p04', brand: 'Samsung', name: 'Galaxy S24 Ultra 256GB',     shop: 'Mercadopamina', price: 7499, oldPrice: 8499, tag: 'Android', image: ecImg('photo-1556656793-08538906a9f8'), rating: 4.7, reviews: 1890, prime: true, specs: ['Tela 6,8" Dynamic AMOLED 2X · 120Hz adaptativo', 'Câmera quad 200MP · zoom óptico 5x · vídeo 8K', 'S Pen integrada · Galaxy AI (tradução, busca, edição)', 'Snapdragon 8 Gen 3 · 256GB · 12GB RAM', 'Chassi titânio · IP68 · 5G · carregamento sem fio'], desc: 'Galaxy S24 Ultra — flagship Samsung com S Pen, câmera de 200MP e Galaxy AI para produtividade e fotografia profissional no bolso.' },
    { id: 'p05', brand: 'Brastemp', name: 'Geladeira Frost Free Inverse 443L',     shop: 'Mercadopamina', price: 4299, oldPrice: 4999, tag: 'Eletro', image: ecImg('photo-1585655097312-7c098090a426'), rating: 4.6, reviews: 678, prime: false, specs: ['443 litros', 'Inox', 'Frost free', 'Painel eletrônico'], desc: 'Geladeira Brastemp inverse com freezer embaixo e controle digital.' },
    { id: 'p06', brand: 'Samsung', name: 'Smart TV 55" Crystal UHD 4K CU8000',     shop: 'Mercadopamina', price: 2499, oldPrice: 2999, tag: 'TV', image: ecImg('photo-1593359677879-a670071ebdbe'), rating: 4.7, reviews: 2890, prime: true, specs: ['Painel 55" 4K UHD 3840×2160', 'HDR10+ · HLG · Motion Xcelerator', 'Sistema Tizen · apps Netflix, Prime, Disney+', '3 HDMI · 1 USB · Wi-Fi · Bluetooth', 'Controle remoto por voz Bixby'], desc: 'Smart TV Samsung Crystal UHD 55" com imagem 4K, HDR e acesso aos principais apps de streaming.' },
    { id: 'p07', brand: 'Apple', name: 'AirPods Pro 2ª geração USB-C',     shop: 'Mercadopamina', price: 1899, oldPrice: 2299, tag: 'Áudio', image: ecImg('photo-1590658268037-6bf12165a8df'), rating: 4.8, reviews: 8340, prime: true, specs: ['Cancelamento ativo de ruído adaptativo (ANC)', 'Modo Transparência adaptativo · áudio espacial personalizado', 'Chip H2 · case MagSafe com carregamento USB-C', 'Até 6h de áudio (30h com estojo de carga)', 'IP54 resistente a suor · busca via rede Find My'], desc: 'AirPods Pro 2ª geração com ANC líder de mercado, áudio espacial e case USB-C — o fone TWS premium da Apple para o dia a dia.' },
    { id: 'p08', brand: 'Nintendo', name: 'Switch OLED 64GB',     shop: 'Mercadopamina', price: 2499, oldPrice: 2799, tag: 'Games', image: ecImg('photo-1621259182978-fbf93132d53d'), rating: 4.8, reviews: 3102, prime: true, specs: ['Tela OLED 7" 1280×720 — cores e contraste superiores', '64GB internos · expansão via cartão microSD', 'Dock inclusa — modo TV até 1080p na sala', 'Joy-Con destacáveis com vibração HD e sensores de movimento', 'Bateria até 9h portátil · suporte a áudio Bluetooth'], desc: 'Nintendo Switch OLED com tela vibrante de 7", modo portátil e TV no mesmo console — ideal para Zelda, Mario e jogos em família.' },
    { id: 'p09', brand: 'Xiaomi', name: 'Robô Aspirador Vacuum S10',     shop: 'Mercadopamina', price: 2199, oldPrice: 2599, tag: 'Casa', image: ecImg('photo-1558317374-a37d8b1b41ff'), rating: 4.5, reviews: 1567, prime: true, specs: ['Mapeamento LDS', 'App Mi Home', '4.000Pa', 'Autovazio'], desc: 'Robô aspirador Xiaomi com navegação a laser e app.' },
    { id: 'p10', brand: 'Nespresso', name: 'Cafeteira Vertuo Pop',     shop: 'Mercadopamina', price: 699, oldPrice: 849, tag: 'Cozinha', image: ecImg('photo-1517668808822-9ebb02f2a0e0'), rating: 4.6, reviews: 2140, prime: true, specs: ['Cápsulas Vertuo', 'Compacta', 'Aquecimento 25s'], desc: 'Cafeteira Nespresso com extração centrífuga e crema generosa.' },
    { id: 'p11', brand: 'Apple', name: 'Apple Watch Series 10 GPS 46mm',     shop: 'Mercadopamina', price: 4299, oldPrice: 4799, tag: 'Wearable', image: ecImg('photo-1434493789847-2f02dc6ca35d'), rating: 4.8, reviews: 1987, prime: true, specs: ['Tela OLED Always-On wide-angle 46mm', 'Chip S10 · GPS de alta precisão', 'Oxímetro · ECG · temperatura do pulso · sono', 'Resistente à água 50m · detecção de queda e acidente', 'watchOS · pulseiras intercambiáveis · iPhone 8s+'], desc: 'Apple Watch Series 10 GPS 46mm — smartwatch premium com monitoramento de saúde avançado, tela sempre ligada e integração total com o ecossistema Apple.' },
    { id: 'p12', brand: 'DJI', name: 'Mini 4 Pro Fly More Combo',     shop: 'Mercadopamina', price: 6499, oldPrice: 7299, tag: 'Creator', image: ecImg('photo-1473968512647-3e447244af8f'), rating: 4.7, reviews: 456, prime: false, specs: ['Câmera 1/1,3" CMOS · vídeo 4K HDR até 60fps', 'Detecção de obstáculos omnidirecional', 'Até 34 min de voo · transmissão O4 até 20 km', 'Combo Fly More com baterias extras e bolsa', 'Peso abaixo de 249g — portátil para viagens'], desc: 'DJI Mini 4 Pro Fly More Combo — drone compacto com câmera 4K HDR, sensores em todas as direções e autonomia para filmagens aéreas profissionais.' },
    { id: 'p13', brand: 'Lenovo', name: 'PC Gamer Ryzen 5 + RTX 4060 16GB',     shop: 'Mercadopamina', price: 5999, oldPrice: 6999, tag: 'Gamer', image: ecImg('photo-1593305841991-05c297ba4575'), rating: 4.7, reviews: 534, prime: true, specs: ['GPU NVIDIA GeForce RTX 4060 8GB GDDR6', 'AMD Ryzen 5 7600 · 6 núcleos / 12 threads', '16GB DDR5 5200MHz · SSD NVMe 512GB', 'Fonte 650W 80 Plus · Windows 11 Home', 'Ideal para 1080p/1440p em alta taxa de quadros'], desc: 'Desktop gamer Lenovo com placa RTX 4060 e Ryzen 5 — roda os lançamentos em alta qualidade com ray tracing.' },
    { id: 'p14', brand: 'Electrolux', name: 'Micro-ondas 34L MI41S',     shop: 'Mercadopamina', price: 699, oldPrice: 849, tag: 'Cozinha', image: ecImg('photo-1574269905862-9a3d95c4d9ac'), rating: 4.5, reviews: 2103, prime: true, specs: ['34 litros', 'Painel integrado', '6 níveis potência'], desc: 'Micro-ondas Electrolux com descongelamento automático.' },
    { id: 'p15', brand: 'Mondial', name: 'Air Fryer Family AFN-40-RI 4L',     shop: 'Mercadopamina', price: 349, oldPrice: 449, tag: 'Mais vendido', image: ecImg('photo-1626082927389-6cd097cdc6ec'), rating: 4.7, reviews: 12400, prime: true, specs: ['Capacidade 4 litros — ideal para família', 'Cesto antiaderente removível · cozinha sem óleo', 'Timer digital até 60 minutos', 'Controle de temperatura ajustável', 'Best-seller Brasil — fritas, nuggets e legumes crocantes'], desc: 'Air Fryer Mondial 4L — fritadeira sem óleo mais vendida do país, prática para o dia a dia com resultado crocante e menos gordura.' },
    { id: 'p16', brand: 'Sony', name: 'WH-1000XM5 — Preto',     shop: 'Mercadopamina', price: 1899, oldPrice: 2299, tag: 'Áudio', image: ecImg('photo-1505740420928-5e560c06d30e'), rating: 4.8, reviews: 5678, prime: true, specs: ['Cancelamento de ruído líder (ANC) adaptativo', 'Drivers de 30mm · áudio Hi-Res LDAC', 'Até 30h de bateria · carga rápida 3 min = 3h', 'Multipoint · 2 dispositivos simultâneos', 'Dobrável · estojo rígido incluso'], desc: 'Headphone over-ear Sony WH-1000XM5 com o melhor cancelamento de ruído da categoria e som premium para viagens e home office.' },
    { id: 'p17', brand: 'Apple', name: 'iPad 11" A16 Wi-Fi 256GB',     shop: 'Mercadopamina', price: 4999, oldPrice: 5499, tag: 'Tablet', image: ecImg('photo-1544244015-0df4b3ffc6b0'), rating: 4.8, reviews: 1432, prime: true, specs: ['Chip Apple A16 Bionic — desempenho fluido', 'Tela Liquid Retina 11" · True Tone · 500 nits', '256GB armazenamento · Wi-Fi 6', 'Compatível com Apple Pencil (USB-C) e Magic Keyboard', 'iPadOS · multitarefa, estudo, trabalho e streaming'], desc: 'iPad 11" com chip A16 e 256GB — tablet versátil para estudo, trabalho criativo e entretenimento com ecossistema Apple.' },
    { id: 'p18', brand: 'Canon', name: 'EOS R50 Kit RF-S18-45mm',     shop: 'Mercadopamina', price: 5499, oldPrice: 6199, tag: 'Foto', image: ecImg('photo-1516035069371-29a1b244cc32'), rating: 4.7, reviews: 389, prime: false, specs: ['24,2MP APS-C', '4K 60p', 'Dual Pixel AF', 'Kit lente'], desc: 'Mirrorless Canon compacta para foto e vídeo 4K.' },
    { id: 'p19', brand: 'Samsung', name: 'Galaxy Watch 7 Bluetooth 44mm',     shop: 'Mercadopamina', price: 1699, oldPrice: 1999, tag: 'Wearable', image: ecImg('photo-1434493789847-2f02dc6ca35d'), rating: 4.6, reviews: 2341, prime: true, specs: ['Wear OS', 'BioActive Sensor', 'GPS', 'Gorilla Glass'], desc: 'Smartwatch Samsung com monitoramento de sono e treino.' },
    { id: 'p20', brand: 'JBL', name: 'Flip 6 — Preta',     shop: 'Mercadopamina', price: 599, oldPrice: 749, tag: 'Áudio', image: ecImg('photo-1608043152269-423dbba4e7e1'), rating: 4.7, reviews: 8450, prime: true, specs: ['Som JBL Pro com graves reforçados', 'IP67 — à prova d\'água e poeira', 'Até 12h de bateria · carregamento USB-C', 'PartyBoost — conecta com outras caixas JBL', 'Formato portátil para praia, piscina e churrasco'], desc: 'JBL Flip 6 preta — caixa Bluetooth compacta com som potente, resistência IP67 e bateria para o dia todo de música.' },
    { id: 'p21', brand: 'Logitech', name: 'MX Master 3S — Grafite',     shop: 'Mercadopamina', price: 549, oldPrice: 699, tag: 'Periféricos', image: ecImg('photo-1527864550417-7fd91fc51a46'), rating: 4.8, reviews: 6780, prime: true, specs: ['8.000 DPI', 'Scroll MagSpeed', 'USB-C', 'Multi-device'], desc: 'Mouse Logitech premium para produtividade e design.' },
    { id: 'p22', brand: 'Dyson', name: 'V15 Detect Absolute',     shop: 'Mercadopamina', price: 4999, oldPrice: 5799, tag: 'Casa', image: ecImg('photo-1558618666-fcd25c85cd64'), rating: 4.8, reviews: 1234, prime: true, specs: ['Laser dust detect', '240AW', '60 min autonomia', 'HEPA'], desc: 'Aspirador sem fio Dyson com laser que revela pó invisível.' },
    { id: 'p23', brand: 'Kindle', name: 'Kindle 11ª geração 16GB',     shop: 'Mercadopamina', price: 499, oldPrice: 599, tag: 'Leitura', image: wikiThumb('9/9e/Amazon_Kindle_11th_generation.jpg', 800), rating: 4.7, reviews: 9870, prime: true, specs: ['Tela 6"', '16GB', 'Luz ajustável', 'Semanas de bateria'], desc: 'Leitor Amazon Kindle leve com tela antirreflexo.' },
    { id: 'p24', brand: 'LG', name: 'Monitor UltraGear 27" 144Hz IPS',     shop: 'Mercadopamina', price: 1299, oldPrice: 1599, tag: 'Monitor', image: wikiThumb('9/9e/Computer_monitor.jpg', 800), rating: 4.7, reviews: 1567, prime: true, specs: ['27" IPS', '144Hz', '1ms', 'FreeSync'], desc: 'Monitor gamer LG com cores precisas e 144Hz.' },
    { id: 'p25', brand: 'Meta', name: 'Quest 3 128GB',     shop: 'Mercadopamina', price: 4999, oldPrice: 5499, tag: 'VR', image: wikiThumb('8/8e/Meta_Quest_3_headset.png', 800), rating: 4.7, reviews: 1234, prime: true, specs: ['Mixed reality', 'Snapdragon XR2 Gen 2', '128GB'], desc: 'Headset Meta Quest 3 com pass-through colorido e jogos VR.' },
    { id: 'p26', brand: 'De\'Longhi', name: 'Dedica EC685 Espresso',     shop: 'Mercadopamina', price: 1899, oldPrice: 2199, tag: 'Barista', image: wikiThumb('4/4e/Espresso_machine.jpg', 800), rating: 4.6, reviews: 678, prime: true, specs: ['15 bar', 'Vaporizador leite', 'Compacta', 'Portafiltro'], desc: 'Máquina De\'Longhi para espresso estilo cafeteria em casa.' },
    { id: 'p27', brand: 'LG', name: 'Smart TV 65" 4K UHD UR8750',     shop: 'Mercadopamina', price: 3299, oldPrice: 3799, tag: 'TV', image: wikiThumb('4/4d/Samsung_4K_UHD_TV.jpg', 800), rating: 4.7, reviews: 1890, prime: true, specs: ['65"', '4K', 'webOS 24', 'HDR10'], desc: 'TV LG grande para sala com controle por voz e apps.' },
    { id: 'p28', brand: 'Philips', name: 'OneBlade Pro QP6550',     shop: 'Mercadopamina', price: 399, oldPrice: 499, tag: 'Beleza', image: ecImg('photo-1503951914875-452162b0f3f1'), rating: 4.6, reviews: 4560, prime: true, specs: ['Tecnologia OneBlade — apara, barbeia e define contornos', 'Bateria recarregável até 120 min de autonomia', '3 pentes de guia (1, 3 e 5 mm)', 'À prova d\'água — uso seco ou no banho', 'Cabeça dupla com revestimento deslizante para a pele'], desc: 'Philips OneBlade Pro — aparador híbrido 3 em 1 para rosto e corpo, com pentes de guia e uso à prova d\'água.' },
    { id: 'p29', brand: 'Consul', name: 'Fogão 5 Bocas Mesa de Vidro',     shop: 'Mercadopamina', price: 1299, oldPrice: 1499, tag: 'Eletro', image: wikiThumb('5/5e/Gas_stove.jpg', 800), rating: 4.5, reviews: 1432, prime: false, specs: ['5 bocas', 'Mesa vidro', 'Forno 86L', 'Acendimento auto'], desc: 'Fogão Consul com mesa de vidro temperado e timer.' },
    { id: 'p30', brand: 'Asus', name: 'ROG Strix G16 RTX 4060 i7',     shop: 'Mercadopamina', price: 8999, oldPrice: 9999, tag: 'Notebook', image: wikiThumb('9/9e/Gaming_laptop.jpg', 800), rating: 4.7, reviews: 890, prime: true, specs: ['Tela 16" WQXGA 165Hz · 100% sRGB', 'Intel Core i7-13650HX · 14 núcleos', 'NVIDIA RTX 4060 8GB · 16GB DDR5', 'SSD 1TB NVMe · Wi-Fi 6E', 'Teclado RGB · Cooler duplo ROG'], desc: 'Notebook gamer Asus ROG Strix G16 com tela 165Hz, RTX 4060 e Intel i7 — portátil para jogar e trabalhar pesado.' },
  ];

  premium.forEach(function (p) {
    p.reviewList = productReviews(p.name);
  });

  var fashion = [
    { id: 'm01', brand: 'Gucci', brandTier: 'griffe', category: 'Acessórios', name: 'Bolsa GG Marmont Matelassê Mini',     shop: 'Mercadopamina', price: 8990, oldPrice: 10990, tag: 'Griffe', image: ecImg('photo-1548036328-c9fa89d128fa'), rating: 4.9, reviews: 412, sizes: ['Único'], color: 'Preto', material: 'Couro matelassê', fit: 'Crossbody', care: 'Limpar com pano seco', specs: ['Couro matelassê com logo GG em relevo', 'Ferragem dourada antiga · fecho coração', 'Corrente ajustável removível (crossbody/ombro)', 'Interior em suede microfibra com bolso', 'Dimensões aprox. 22×13×6 cm'], desc: 'Bolsa Gucci GG Marmont Mini — ícone de luxo em couro matelassê preto com ferragem dourada e corrente versátil.' },
    { id: 'm02', brand: 'Louis Vuitton', brandTier: 'griffe', category: 'Acessórios', name: 'Neverfull MM Monogram',     shop: 'Mercadopamina', price: 12990, oldPrice: 14500, tag: 'Griffe', image: ecImg('photo-1566150905458-1bf1fc113f0d'), rating: 4.9, reviews: 890, sizes: ['Único'], color: 'Monograma', material: 'Canvas Monogram', fit: 'Tote', care: 'Evitar umidade prolongada', specs: ['Canvas Monogram revestido e resistente', 'Formato tote MM — trabalho, viagem e casual', 'Alças de couro natural envelhecido', 'Cordão lateral para ajustar o volume interno', 'Forro têxtil · bolso com zíper removível'], desc: 'Louis Vuitton Neverfull MM Monogram — bolsa tote icônica desde 2007, espaçosa e versátil para o dia a dia com status de griffe.' },
    { id: 'm03', brand: 'Chanel', brandTier: 'griffe', category: 'Acessórios', name: 'Classic Flap Média — Caviar Preto',     shop: 'Mercadopamina', price: 38900, oldPrice: 42000, tag: 'Alta costura', image: ecImg('photo-1548036328-c9fa89d128fa'), rating: 5.0, reviews: 156, sizes: ['Único'], color: 'Preto', material: 'Couro caviar', fit: 'Ombro/crossbody', care: 'Guardar com papel manteiga', desc: 'Classic Flap Chanel com corrente dourada e fecho CC — peça de investimento.' },
    { id: 'm04', brand: 'Balenciaga', brandTier: 'griffe', category: 'Calçados', name: 'Triple S Sneaker — Branco/Preto',     shop: 'Mercadopamina', price: 6990, oldPrice: 8200, tag: 'Griffe', image: ecImg('photo-1549298916-b41d501d3772'), rating: 4.7, reviews: 678, sizes: ['38', '39', '40', '41', '42'], color: 'Branco/Preto', material: 'Couro/mesh', fit: 'Chunky — número normal', care: 'Escova macia', desc: 'Tênis Balenciaga Triple S que definiu o movimento chunky sneaker.' },
    { id: 'm05', brand: 'Prada', brandTier: 'griffe', category: 'Calçados', name: 'America\'s Cup Sneaker',     shop: 'Mercadopamina', price: 5490, oldPrice: 6200, tag: 'Griffe', image: ecImg('photo-1608253813970-eee5a0955d81'), rating: 4.8, reviews: 234, sizes: ['37', '38', '39', '40', '41'], color: 'Branco', material: 'Couro e mesh', fit: 'Fiel ao tamanho', care: 'Impermeabilizar', desc: 'Sneaker Prada America\'s Cup com triângulo icônico lateral.' },
    { id: 'm06', brand: 'Versace', brandTier: 'griffe', category: 'Acessórios', name: 'Óculos Medusa Biggie — Dourado',     shop: 'Mercadopamina', price: 2490, oldPrice: 3100, tag: 'Griffe', image: ecImg('photo-1572635196237-14b3f281503f'), rating: 4.6, reviews: 189, sizes: ['Único'], color: 'Dourado', material: 'Metal acetato', fit: 'Unissex', care: 'Estojo rígido incluso', desc: 'Óculos Versace com detalhe Medusa e lentes UV400.' },
    { id: 'm07', brand: 'Nike', brandTier: 'premium', category: 'Calçados', name: 'Air Max 90 Essential — Branco',     shop: 'Mercadopamina', price: 799, oldPrice: 999, tag: 'Nike', image: ecImg('photo-1542291026-7eec264c27ff'), rating: 4.8, reviews: 12400, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Branco/Cinza', material: 'Couro e mesh', fit: 'Fiel ao tamanho', care: 'Limpar com escova úmida', specs: ['Amortecimento Nike Air visível no calcanhar', 'Cabedal em couro e mesh respirável', 'Solado borracha waffle — tração e durabilidade', 'Entressola Cushlon para conforto diário', 'Silhueta clássica anos 90 — streetwear e casual'], desc: 'Nike Air Max 90 Essential em branco/cinza — o sneaker que definiu uma geração, com bolha Air icônica e conforto para o dia a dia.' },
    { id: 'm08', brand: 'Adidas', brandTier: 'premium', category: 'Calçados', name: 'Ultraboost 22 — Core Black',     shop: 'Mercadopamina', price: 899, oldPrice: 1199, tag: 'Adidas', image: ecImg('photo-1600185365926-3a2ce3cdb9eb'), rating: 4.7, reviews: 8900, sizes: ['36', '37', '38', '39', '40', '41', '42'], color: 'Preto', material: 'Primeknit + Boost', fit: 'Ajuste sock-like', care: 'Lavar à mão', specs: ['Cabedal Primeknit+ respirável e adaptável', 'Entressola Boost — retorno de energia a cada passo', 'Solado Continental™ — tração em piso molhado', 'Core Black · visual urbano atemporal', 'Versátil para corrida, caminhada e lifestyle'], desc: 'Adidas Ultraboost 22 Core Black — tênis com tecnologia Boost e Primeknit+ para conforto máximo na corrida e no dia a dia urbano.' },
    { id: 'm09', brand: 'New Balance', brandTier: 'premium', category: 'Calçados', name: '550 Branco/Verde',     shop: 'Mercadopamina', price: 699, oldPrice: 899, tag: 'NB', image: ecImg('photo-1608667509904-b82b1ae1df4b'), rating: 4.7, reviews: 5600, sizes: ['36', '37', '38', '39', '40', '41'], color: 'Branco/Verde', material: 'Couro sintético', fit: 'Número normal', care: 'Pano úmido', desc: 'New Balance 550 retro basketball — viral no streetwear.' },
    { id: 'm10', brand: 'Zara', brandTier: 'premium', category: 'Feminino', name: 'Trench Coat Oversized Bege',     shop: 'Mercadopamina', price: 499, oldPrice: 699, tag: 'Zara', image: ecImg('photo-1591047139829-d91aecb6caea'), rating: 4.6, reviews: 3400, sizes: ['P', 'M', 'G'], color: 'Bege', material: 'Algodão poliéster', fit: 'Oversized', care: 'Lavar a seco', desc: 'Trench coat Zara oversized — peça-chave de guarda-roupa cápsula.' },
    { id: 'm11', brand: 'Mango', brandTier: 'premium', category: 'Feminino', name: 'Vestido Midi Satinado Preto',     shop: 'Mercadopamina', price: 349, oldPrice: 499, tag: 'Mango', image: ecImg('photo-1595777457583-95e059d581b8'), rating: 4.7, reviews: 2100, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Poliéster acetinado', fit: 'Regular', care: 'Lavar à mão', specs: ['Comprimento midi — joelho a tornozelo', 'Tecido acetinado com brilho elegante', 'Manga curta · decote redondo', 'Forro leve · zíper lateral invisível', 'Ideal para festas, jantares e eventos sociais'], desc: 'Vestido Mango midi satinado preto — caimento fluido e acabamento acetinado para ocasiões especiais sem abrir mão do conforto.' },
    { id: 'm12', brand: 'Lacoste', brandTier: 'premium', category: 'Masculino', name: 'Polo Classic Fit — Branco',     shop: 'Mercadopamina', price: 449, oldPrice: 599, tag: 'Lacoste', image: ecImg('photo-1621072156002-e2fccdc0b176'), rating: 4.8, reviews: 6700, sizes: ['P', 'M', 'G', 'GG'], color: 'Branco', material: 'Algodão piquet', fit: 'Classic fit', care: 'Máq. 30°C', specs: ['100% algodão piquet premium', 'Crocodilo Lacoste bordado no peito', 'Modelagem Classic Fit — caimento tradicional', 'Gola com botões · mangas curtas', 'Ícone francês desde 1933 — casual elegante'], desc: 'Polo Lacoste Classic Fit branco com crocodilo bordado — peça atemporal de algodão piquet para o guarda-roupa masculino.' },
    { id: 'm13', brand: 'H&M', brandTier: 'popular', category: 'Feminino', name: 'Camiseta Algodão Premium Branca',     shop: 'Mercadopamina', price: 59.9, oldPrice: 79.9, tag: 'H&M', image: ecImg('photo-1576566588028-4147f3842f27'), rating: 4.5, reviews: 18900, sizes: ['P', 'M', 'G', 'GG'], color: 'Branco', material: '100% algodão', fit: 'Regular', care: 'Máq. 40°C', specs: ['100% algodão orgânico certificado', 'Malha premium 180 g/m² — toque macio', 'Gola ribana reforçada · costura dupla', 'Modelagem regular unissex', 'Básica versátil — do casual ao layering'], desc: 'Camiseta H&M em algodão premium branco — peça-coringa do guarda-roupa com caimento confortável e qualidade acima da linha básica.' },
    { id: 'm14', brand: 'Renner', brandTier: 'popular', category: 'Feminino', name: 'Calça Jeans Wide Leg Azul Médio',     shop: 'Mercadopamina', price: 129.9, oldPrice: 179.9, tag: 'Renner', image: ecImg('photo-1624378439575-d8705ad7ae80'), rating: 4.6, reviews: 8900, sizes: ['36', '38', '40', '42', '44'], color: 'Azul médio', material: 'Algodão elastano', fit: 'Wide leg cintura alta', care: 'Lavar do avesso', specs: ['Modelagem wide leg cintura alta', 'Algodão com elastano — conforto e caimento', 'Azul médio versátil para o dia a dia', 'Cós estruturado · bolsos frontais e traseiros', 'Tendência denim — combina com tênis, sandália e salto'], desc: 'Calça jeans Renner wide leg azul médio — modelagem tendência com cintura alta, confortável e fácil de combinar no guarda-roupa.' },
    { id: 'm15', brand: 'C&A', brandTier: 'popular', category: 'Feminino', name: 'Blusa Manga Longa Ribana',     shop: 'Mercadopamina', price: 69.9, oldPrice: 99.9, tag: 'C&A', image: ecImg('photo-1596755094514-f87e34085b2c'), rating: 4.4, reviews: 5600, sizes: ['P', 'M', 'G'], color: 'Nude', material: 'Viscose elastano', fit: 'Ajustada', care: 'Máq. delicado', desc: 'Blusa C&A em ribana macia — segunda pele para o dia a dia.' },
    { id: 'm16', brand: 'Riachuelo', brandTier: 'popular', category: 'Calçados', name: 'Sandália Flat Metalizada Dourada',     shop: 'Mercadopamina', price: 79.9, oldPrice: 119.9, tag: 'Riachuelo', image: ecImg('photo-1603487742874-03f67dfec1a3'), rating: 4.3, reviews: 4200, sizes: ['35', '36', '37', '38', '39'], color: 'Dourado', material: 'Sintético', fit: 'Fiel', care: 'Pano seco', desc: 'Sandália Riachuelo flat metalizada para o verão brasileiro.' },
    { id: 'm17', brand: 'Farm', brandTier: 'premium', category: 'Feminino', name: 'Vestido Estampa Tropical',     shop: 'Mercadopamina', price: 389, oldPrice: 499, tag: 'Farm', image: ecImg('photo-1596780209987-0b89b4369ec9'), rating: 4.8, reviews: 1890, sizes: ['P', 'M', 'G'], color: 'Multicolor', material: 'Viscose', fit: 'Fluido', care: 'Máq. delicado', desc: 'Vestido Farm com estampa exclusiva brasileira — marca carioca icônica.' },
    { id: 'm18', brand: 'Melissa', brandTier: 'popular', category: 'Calçados', name: 'Possession — Rosa Glitter',     shop: 'Mercadopamina', price: 199, oldPrice: 249, tag: 'Melissa', image: ecImg('photo-1603487742874-03f67dfec1a3'), rating: 4.7, reviews: 7800, sizes: ['35', '36', '37', '38', '39', '40'], color: 'Rosa glitter', material: 'Melflex', fit: 'Fiel', care: 'Água e sabão', desc: 'Sandália Melissa Possession — cheiro característico e conforto.' },
    { id: 'm19', brand: 'Shoulder', brandTier: 'premium', category: 'Feminino', name: 'Cropped Tricot Off-White',     shop: 'Mercadopamina', price: 299, oldPrice: 399, tag: 'Shoulder', image: ecImg('photo-1596755094514-f87e34085b2c'), rating: 4.6, reviews: 1200, sizes: ['P', 'M', 'G'], color: 'Off-white', material: 'Tricot algodão', fit: 'Cropped', care: 'Lavar à mão', desc: 'Cropped Shoulder em tricot — marca brasileira premium contemporânea.' },
    { id: 'm20', brand: 'Marisa', brandTier: 'popular', category: 'Feminino', name: 'Sutiã Conforto Microfibra',     shop: 'Mercadopamina', price: 49.9, oldPrice: 69.9, tag: 'Marisa', image: ecImg('photo-1594753792364-f79b2ecf8296'), rating: 4.4, reviews: 6700, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Microfibra', fit: 'Conforto sem aro', care: 'Máq. delicado', desc: 'Sutiã Marisa microfibra sem costura — conforto para o dia a dia.' },
    { id: 'm21', brand: 'Puma', brandTier: 'premium', category: 'Masculino', name: 'Camisa Palmeiras I 2025 Torcedor',     shop: 'Mercadopamina', price: 349, oldPrice: 399, tag: 'Puma', image: ecImg('photo-1579952363873-27f3bade9f55'), rating: 4.8, reviews: 4500, sizes: ['P', 'M', 'G', 'GG'], color: 'Verde', material: 'Poliéster dry-fit', fit: 'Torcedor', care: 'Não usar alvejante', desc: 'Camisa oficial Puma Palmeiras temporada 2025 — torcedor.' },
    { id: 'm22', brand: 'Ray-Ban', brandTier: 'premium', category: 'Acessórios', name: 'Aviador Classic RB3025 — Dourado',     shop: 'Mercadopamina', price: 699, oldPrice: 849, tag: 'Ray-Ban', image: ecImg('photo-1572635196237-14b3f281503f'), rating: 4.8, reviews: 9200, sizes: ['Único'], color: 'Dourado/Verde G-15', material: 'Metal', fit: 'Unissex', care: 'Estojo + flanela', specs: ['Modelo RB3025 Classic — armação aviador', 'Lentes G-15 verde — proteção UV 100%', 'Armação metal dourado · hastes ajustáveis', 'Pontas em acetato para conforto nas orelhas', 'Estojo rígido e flanela de limpeza inclusos'], desc: 'Ray-Ban Aviador RB3025 dourado com lentes G-15 — o óculos mais icônico do mundo, criado para pilotos e adotado por gerações.' },
    { id: 'm23', brand: 'Havaianas', brandTier: 'popular', category: 'Calçados', name: 'Top Brasil — Azul Naval',     shop: 'Mercadopamina', price: 39.9, oldPrice: 49.9, tag: 'Havaianas', image: ecImg('photo-1603487742874-03f67dfec1a3'), rating: 4.9, reviews: 23400, sizes: ['35/36', '37/38', '39/40', '41/42'], color: 'Azul naval', material: 'Borracha', fit: 'Fiel', care: 'Lavar água fria', desc: 'Havaianas Top Brasil — chinelo mais vendido do país.' },
    { id: 'm24', brand: 'Colcci', brandTier: 'premium', category: 'Masculino', name: 'Camiseta Logo Bordado Preta',     shop: 'Mercadopamina', price: 159, oldPrice: 199, tag: 'Colcci', image: ecImg('photo-1521572163474-e1f1ad5812d0'), rating: 4.5, reviews: 2100, sizes: ['P', 'M', 'G', 'GG'], color: 'Preto', material: 'Algodão premium', fit: 'Slim', care: 'Máq. 30°C do avesso', desc: 'Camiseta Colcci com logo bordado — streetwear brasileiro premium.' },
  ];

  fashion.forEach(function (p) {
    p.reviewList = fashionReviews(p.name, p.brand);
    p.specs = [
      'Marca: ' + p.brand,
      'Cor: ' + p.color,
      'Material: ' + p.material,
      'Caimento: ' + p.fit,
      'Cuidados: ' + p.care,
    ];
  });

  if (w.DOPAMINA_PHOTOS && w.DOPAMINA_PHOTOS.apply) {
    [express, premium, fashion].forEach(function (arr) {
      arr.forEach(function (p) {
        delete p.image;
      });
    });
    w.DOPAMINA_PHOTOS.apply(express);
    w.DOPAMINA_PHOTOS.apply(premium);
    w.DOPAMINA_PHOTOS.apply(fashion);
  }

  w.DOPAMINA_CATALOG = { express: express, premium: premium, fashion: fashion };
})(window);
